package com.fh.entity.amsmodel;

import java.util.Date;

public class Apply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply.APPLY_ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private Integer applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply.APPLY_WHY
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private String applyWhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply.USER_ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply.APPLY_TIME
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply.returntime
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private Date returntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply.descs
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private String descs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply.APPLY_ID
     *
     * @return the value of ams_apply.APPLY_ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply.APPLY_ID
     *
     * @param applyId the value for ams_apply.APPLY_ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply.APPLY_WHY
     *
     * @return the value of ams_apply.APPLY_WHY
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public String getApplyWhy() {
        return applyWhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply.APPLY_WHY
     *
     * @param applyWhy the value for ams_apply.APPLY_WHY
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setApplyWhy(String applyWhy) {
        this.applyWhy = applyWhy == null ? null : applyWhy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply.USER_ID
     *
     * @return the value of ams_apply.USER_ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply.USER_ID
     *
     * @param userId the value for ams_apply.USER_ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply.APPLY_TIME
     *
     * @return the value of ams_apply.APPLY_TIME
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply.APPLY_TIME
     *
     * @param applyTime the value for ams_apply.APPLY_TIME
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply.returntime
     *
     * @return the value of ams_apply.returntime
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public Date getReturntime() {
        return returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply.returntime
     *
     * @param returntime the value for ams_apply.returntime
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setReturntime(Date returntime) {
        this.returntime = returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply.descs
     *
     * @return the value of ams_apply.descs
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply.descs
     *
     * @param descs the value for ams_apply.descs
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

	@Override
	public String toString() {
		return "Apply [applyId=" + applyId + ", applyWhy=" + applyWhy + ", userId=" + userId + ", applyTime="
				+ applyTime + ", returntime=" + returntime + ", descs=" + descs + "]";
	}
    
}