package com.fh.entity.amsmodel;

public class ApplyFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply_file.ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply_file.Apply_id
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private Integer applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_apply_file.file_id
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    private Integer fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply_file.ID
     *
     * @return the value of ams_apply_file.ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply_file.ID
     *
     * @param id the value for ams_apply_file.ID
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply_file.Apply_id
     *
     * @return the value of ams_apply_file.Apply_id
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply_file.Apply_id
     *
     * @param applyId the value for ams_apply_file.Apply_id
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_apply_file.file_id
     *
     * @return the value of ams_apply_file.file_id
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_apply_file.file_id
     *
     * @param fileId the value for ams_apply_file.file_id
     *
     * @mbggenerated Mon Jul 04 15:29:41 CST 2016
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }
}