package com.fh.entity.amsmodel;

public class ArchDistributeFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute_file.id
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute_file.DISTRIBUTE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer distributeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute_file.FILE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute_file.stute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer stute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute_file.mess
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private String mess;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute_file.id
     *
     * @return the value of ams_archdistribute_file.id
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute_file.id
     *
     * @param id the value for ams_archdistribute_file.id
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute_file.DISTRIBUTE_ID
     *
     * @return the value of ams_archdistribute_file.DISTRIBUTE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getDistributeId() {
        return distributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute_file.DISTRIBUTE_ID
     *
     * @param distributeId the value for ams_archdistribute_file.DISTRIBUTE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setDistributeId(Integer distributeId) {
        this.distributeId = distributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute_file.FILE_ID
     *
     * @return the value of ams_archdistribute_file.FILE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute_file.FILE_ID
     *
     * @param fileId the value for ams_archdistribute_file.FILE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute_file.stute
     *
     * @return the value of ams_archdistribute_file.stute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getStute() {
        return stute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute_file.stute
     *
     * @param stute the value for ams_archdistribute_file.stute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setStute(Integer stute) {
        this.stute = stute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute_file.mess
     *
     * @return the value of ams_archdistribute_file.mess
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public String getMess() {
        return mess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute_file.mess
     *
     * @param mess the value for ams_archdistribute_file.mess
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setMess(String mess) {
        this.mess = mess == null ? null : mess.trim();
    }
}