package com.fh.entity.amsmodel;

import java.util.Date;

public class ArchDistribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.DISTRIBUTE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer distributeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.DISTRIBUTE_TIME
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Date distributeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.APPLY_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.DISTRIBUTE_REMARK
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private String distributeRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.USER_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.user_id2
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private String userId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_archdistribute.type
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.DISTRIBUTE_ID
     *
     * @return the value of ams_archdistribute.DISTRIBUTE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getDistributeId() {
        return distributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.DISTRIBUTE_ID
     *
     * @param distributeId the value for ams_archdistribute.DISTRIBUTE_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setDistributeId(Integer distributeId) {
        this.distributeId = distributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.DISTRIBUTE_TIME
     *
     * @return the value of ams_archdistribute.DISTRIBUTE_TIME
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Date getDistributeTime() {
        return distributeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.DISTRIBUTE_TIME
     *
     * @param distributeTime the value for ams_archdistribute.DISTRIBUTE_TIME
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setDistributeTime(Date distributeTime) {
        this.distributeTime = distributeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.APPLY_ID
     *
     * @return the value of ams_archdistribute.APPLY_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.APPLY_ID
     *
     * @param applyId the value for ams_archdistribute.APPLY_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.DISTRIBUTE_REMARK
     *
     * @return the value of ams_archdistribute.DISTRIBUTE_REMARK
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public String getDistributeRemark() {
        return distributeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.DISTRIBUTE_REMARK
     *
     * @param distributeRemark the value for ams_archdistribute.DISTRIBUTE_REMARK
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setDistributeRemark(String distributeRemark) {
        this.distributeRemark = distributeRemark == null ? null : distributeRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.USER_ID
     *
     * @return the value of ams_archdistribute.USER_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.USER_ID
     *
     * @param userId the value for ams_archdistribute.USER_ID
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.user_id2
     *
     * @return the value of ams_archdistribute.user_id2
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public String getUserId2() {
        return userId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.user_id2
     *
     * @param userId2 the value for ams_archdistribute.user_id2
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setUserId2(String userId2) {
        this.userId2 = userId2 == null ? null : userId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_archdistribute.type
     *
     * @return the value of ams_archdistribute.type
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_archdistribute.type
     *
     * @param type the value for ams_archdistribute.type
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

	@Override
	public String toString() {
		return "ArchDistribute [distributeId=" + distributeId + ", distributeTime=" + distributeTime + ", applyId="
				+ applyId + ", distributeRemark=" + distributeRemark + ", userId=" + userId + ", userId2=" + userId2
				+ ", type=" + type + "]";
	}
    
    
}