package com.fh.entity.amsmodel;

public class Cdm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Integer storageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.CD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String cdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.CD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String cdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.VOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String actvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.UNIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.CD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String cdLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.CD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String cdLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_cdm.CD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String cdRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.STORAGE_ID
     *
     * @return the value of ams_cdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Integer getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.STORAGE_ID
     *
     * @param storageId the value for ams_cdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setStorageId(Integer storageId) {
        this.storageId = storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.CD_ID
     *
     * @return the value of ams_cdm.CD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getCdId() {
        return cdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.CD_ID
     *
     * @param cdId the value for ams_cdm.CD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setCdId(String cdId) {
        this.cdId = cdId == null ? null : cdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.CD_NAME
     *
     * @return the value of ams_cdm.CD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getCdName() {
        return cdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.CD_NAME
     *
     * @param cdName the value for ams_cdm.CD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setCdName(String cdName) {
        this.cdName = cdName == null ? null : cdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.VOLUME
     *
     * @return the value of ams_cdm.VOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.VOLUME
     *
     * @param volume the value for ams_cdm.VOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.ACTVOLUME
     *
     * @return the value of ams_cdm.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getActvolume() {
        return actvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.ACTVOLUME
     *
     * @param actvolume the value for ams_cdm.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setActvolume(String actvolume) {
        this.actvolume = actvolume == null ? null : actvolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.UNIT
     *
     * @return the value of ams_cdm.UNIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.UNIT
     *
     * @param unit the value for ams_cdm.UNIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.CD_LOCATION
     *
     * @return the value of ams_cdm.CD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getCdLocation() {
        return cdLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.CD_LOCATION
     *
     * @param cdLocation the value for ams_cdm.CD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setCdLocation(String cdLocation) {
        this.cdLocation = cdLocation == null ? null : cdLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.CD_LIMIT
     *
     * @return the value of ams_cdm.CD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getCdLimit() {
        return cdLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.CD_LIMIT
     *
     * @param cdLimit the value for ams_cdm.CD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setCdLimit(String cdLimit) {
        this.cdLimit = cdLimit == null ? null : cdLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_cdm.CD_REMARK
     *
     * @return the value of ams_cdm.CD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getCdRemark() {
        return cdRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_cdm.CD_REMARK
     *
     * @param cdRemark the value for ams_cdm.CD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setCdRemark(String cdRemark) {
        this.cdRemark = cdRemark == null ? null : cdRemark.trim();
    }
}