package com.fh.entity.amsmodel;

public class Fdm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Integer storageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_S
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_G
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_YEAR
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.PAGE
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_fdm.FD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String fdLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.STORAGE_ID
     *
     * @return the value of ams_fdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Integer getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.STORAGE_ID
     *
     * @param storageId the value for ams_fdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setStorageId(Integer storageId) {
        this.storageId = storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_ID
     *
     * @return the value of ams_fdm.FD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdId() {
        return fdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_ID
     *
     * @param fdId the value for ams_fdm.FD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdId(String fdId) {
        this.fdId = fdId == null ? null : fdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_S
     *
     * @return the value of ams_fdm.FD_S
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdS() {
        return fdS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_S
     *
     * @param fdS the value for ams_fdm.FD_S
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdS(String fdS) {
        this.fdS = fdS == null ? null : fdS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_G
     *
     * @return the value of ams_fdm.FD_G
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdG() {
        return fdG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_G
     *
     * @param fdG the value for ams_fdm.FD_G
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdG(String fdG) {
        this.fdG = fdG == null ? null : fdG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_NAME
     *
     * @return the value of ams_fdm.FD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdName() {
        return fdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_NAME
     *
     * @param fdName the value for ams_fdm.FD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdName(String fdName) {
        this.fdName = fdName == null ? null : fdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_YEAR
     *
     * @return the value of ams_fdm.FD_YEAR
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdYear() {
        return fdYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_YEAR
     *
     * @param fdYear the value for ams_fdm.FD_YEAR
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdYear(String fdYear) {
        this.fdYear = fdYear == null ? null : fdYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.PAGE
     *
     * @return the value of ams_fdm.PAGE
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.PAGE
     *
     * @param page the value for ams_fdm.PAGE
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_LIMIT
     *
     * @return the value of ams_fdm.FD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdLimit() {
        return fdLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_LIMIT
     *
     * @param fdLimit the value for ams_fdm.FD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdLimit(String fdLimit) {
        this.fdLimit = fdLimit == null ? null : fdLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_REMARK
     *
     * @return the value of ams_fdm.FD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdRemark() {
        return fdRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_REMARK
     *
     * @param fdRemark the value for ams_fdm.FD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdRemark(String fdRemark) {
        this.fdRemark = fdRemark == null ? null : fdRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_fdm.FD_LOCATION
     *
     * @return the value of ams_fdm.FD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getFdLocation() {
        return fdLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_fdm.FD_LOCATION
     *
     * @param fdLocation the value for ams_fdm.FD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setFdLocation(String fdLocation) {
        this.fdLocation = fdLocation == null ? null : fdLocation.trim();
    }
}