package com.fh.entity.amsmodel;

public class FileXzqh {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_xzqh.XZQH_PAC
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    private String xzqhPac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_xzqh.PAC
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    private String pac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_xzqh.PAC_NAME
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    private String pacName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_xzqh.REMARK
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_xzqh.XZQH_PAC
     *
     * @return the value of ams_file_xzqh.XZQH_PAC
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public String getXzqhPac() {
        return xzqhPac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_xzqh.XZQH_PAC
     *
     * @param xzqhPac the value for ams_file_xzqh.XZQH_PAC
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public void setXzqhPac(String xzqhPac) {
        this.xzqhPac = xzqhPac == null ? null : xzqhPac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_xzqh.PAC
     *
     * @return the value of ams_file_xzqh.PAC
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public String getPac() {
        return pac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_xzqh.PAC
     *
     * @param pac the value for ams_file_xzqh.PAC
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public void setPac(String pac) {
        this.pac = pac == null ? null : pac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_xzqh.PAC_NAME
     *
     * @return the value of ams_file_xzqh.PAC_NAME
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public String getPacName() {
        return pacName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_xzqh.PAC_NAME
     *
     * @param pacName the value for ams_file_xzqh.PAC_NAME
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public void setPacName(String pacName) {
        this.pacName = pacName == null ? null : pacName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_xzqh.REMARK
     *
     * @return the value of ams_file_xzqh.REMARK
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_xzqh.REMARK
     *
     * @param remark the value for ams_file_xzqh.REMARK
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}