package com.fh.entity.amsmodel;

public class FileDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_detail.FILEDETAIL_ID
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    private Integer filedetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_detail.DETAIL
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_detail.FILEDETAIL_TEXT
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    private String filedetailText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file_detail.FILEDETAIL_URL
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    private String filedetailUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_detail.FILEDETAIL_ID
     *
     * @return the value of ams_file_detail.FILEDETAIL_ID
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public Integer getFiledetailId() {
        return filedetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_detail.FILEDETAIL_ID
     *
     * @param filedetailId the value for ams_file_detail.FILEDETAIL_ID
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public void setFiledetailId(Integer filedetailId) {
        this.filedetailId = filedetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_detail.DETAIL
     *
     * @return the value of ams_file_detail.DETAIL
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_detail.DETAIL
     *
     * @param detail the value for ams_file_detail.DETAIL
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_detail.FILEDETAIL_TEXT
     *
     * @return the value of ams_file_detail.FILEDETAIL_TEXT
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public String getFiledetailText() {
        return filedetailText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_detail.FILEDETAIL_TEXT
     *
     * @param filedetailText the value for ams_file_detail.FILEDETAIL_TEXT
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public void setFiledetailText(String filedetailText) {
        this.filedetailText = filedetailText == null ? null : filedetailText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file_detail.FILEDETAIL_URL
     *
     * @return the value of ams_file_detail.FILEDETAIL_URL
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public String getFiledetailUrl() {
        return filedetailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file_detail.FILEDETAIL_URL
     *
     * @param filedetailUrl the value for ams_file_detail.FILEDETAIL_URL
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    public void setFiledetailUrl(String filedetailUrl) {
        this.filedetailUrl = filedetailUrl == null ? null : filedetailUrl.trim();
    }
}