package com.fh.entity.amsmodel;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILE_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.RC_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private Integer rcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILE_NAME
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.IFDIGIT
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String ifdigit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.DATAFORM
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String dataform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILE_URL
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.VOLUME
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.UNIT
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.IFARCHIVE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String ifarchive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILE_TYPE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.SCALE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.GET_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String getId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILE_REMARK
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.PERMISSION_CLASS
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String permissionClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.CREATIONDATE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.COVERAGE_IDS
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String coverageIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.COVERAGE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String coverage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.YEAR
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILEDETAIL_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private Integer filedetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILEATTR1
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileattr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILEATTR2
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileattr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_file.FILEATTR3
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    private String fileattr3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILE_ID
     *
     * @return the value of ams_file.FILE_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILE_ID
     *
     * @param fileId the value for ams_file.FILE_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.RC_ID
     *
     * @return the value of ams_file.RC_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public Integer getRcId() {
        return rcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.RC_ID
     *
     * @param rcId the value for ams_file.RC_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setRcId(Integer rcId) {
        this.rcId = rcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILE_NAME
     *
     * @return the value of ams_file.FILE_NAME
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILE_NAME
     *
     * @param fileName the value for ams_file.FILE_NAME
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.IFDIGIT
     *
     * @return the value of ams_file.IFDIGIT
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getIfdigit() {
        return ifdigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.IFDIGIT
     *
     * @param ifdigit the value for ams_file.IFDIGIT
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setIfdigit(String ifdigit) {
        this.ifdigit = ifdigit == null ? null : ifdigit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.DATAFORM
     *
     * @return the value of ams_file.DATAFORM
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getDataform() {
        return dataform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.DATAFORM
     *
     * @param dataform the value for ams_file.DATAFORM
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setDataform(String dataform) {
        this.dataform = dataform == null ? null : dataform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILE_URL
     *
     * @return the value of ams_file.FILE_URL
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILE_URL
     *
     * @param fileUrl the value for ams_file.FILE_URL
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.VOLUME
     *
     * @return the value of ams_file.VOLUME
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.VOLUME
     *
     * @param volume the value for ams_file.VOLUME
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.UNIT
     *
     * @return the value of ams_file.UNIT
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.UNIT
     *
     * @param unit the value for ams_file.UNIT
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.IFARCHIVE
     *
     * @return the value of ams_file.IFARCHIVE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getIfarchive() {
        return ifarchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.IFARCHIVE
     *
     * @param ifarchive the value for ams_file.IFARCHIVE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setIfarchive(String ifarchive) {
        this.ifarchive = ifarchive == null ? null : ifarchive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILE_TYPE
     *
     * @return the value of ams_file.FILE_TYPE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILE_TYPE
     *
     * @param fileType the value for ams_file.FILE_TYPE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.SCALE
     *
     * @return the value of ams_file.SCALE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.SCALE
     *
     * @param scale the value for ams_file.SCALE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.GET_ID
     *
     * @return the value of ams_file.GET_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getGetId() {
        return getId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.GET_ID
     *
     * @param getId the value for ams_file.GET_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setGetId(String getId) {
        this.getId = getId == null ? null : getId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILE_REMARK
     *
     * @return the value of ams_file.FILE_REMARK
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileRemark() {
        return fileRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILE_REMARK
     *
     * @param fileRemark the value for ams_file.FILE_REMARK
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileRemark(String fileRemark) {
        this.fileRemark = fileRemark == null ? null : fileRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.PERMISSION_CLASS
     *
     * @return the value of ams_file.PERMISSION_CLASS
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getPermissionClass() {
        return permissionClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.PERMISSION_CLASS
     *
     * @param permissionClass the value for ams_file.PERMISSION_CLASS
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setPermissionClass(String permissionClass) {
        this.permissionClass = permissionClass == null ? null : permissionClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.CREATIONDATE
     *
     * @return the value of ams_file.CREATIONDATE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.CREATIONDATE
     *
     * @param creationdate the value for ams_file.CREATIONDATE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setCreationdate(String creationdate) {
        this.creationdate = creationdate == null ? null : creationdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.COVERAGE_IDS
     *
     * @return the value of ams_file.COVERAGE_IDS
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getCoverageIds() {
        return coverageIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.COVERAGE_IDS
     *
     * @param coverageIds the value for ams_file.COVERAGE_IDS
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setCoverageIds(String coverageIds) {
        this.coverageIds = coverageIds == null ? null : coverageIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.COVERAGE
     *
     * @return the value of ams_file.COVERAGE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.COVERAGE
     *
     * @param coverage the value for ams_file.COVERAGE
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setCoverage(String coverage) {
        this.coverage = coverage == null ? null : coverage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.YEAR
     *
     * @return the value of ams_file.YEAR
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.YEAR
     *
     * @param year the value for ams_file.YEAR
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILEDETAIL_ID
     *
     * @return the value of ams_file.FILEDETAIL_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public Integer getFiledetailId() {
        return filedetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILEDETAIL_ID
     *
     * @param filedetailId the value for ams_file.FILEDETAIL_ID
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFiledetailId(Integer filedetailId) {
        this.filedetailId = filedetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILEATTR1
     *
     * @return the value of ams_file.FILEATTR1
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileattr1() {
        return fileattr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILEATTR1
     *
     * @param fileattr1 the value for ams_file.FILEATTR1
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileattr1(String fileattr1) {
        this.fileattr1 = fileattr1 == null ? null : fileattr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILEATTR2
     *
     * @return the value of ams_file.FILEATTR2
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileattr2() {
        return fileattr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILEATTR2
     *
     * @param fileattr2 the value for ams_file.FILEATTR2
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileattr2(String fileattr2) {
        this.fileattr2 = fileattr2 == null ? null : fileattr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_file.FILEATTR3
     *
     * @return the value of ams_file.FILEATTR3
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public String getFileattr3() {
        return fileattr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_file.FILEATTR3
     *
     * @param fileattr3 the value for ams_file.FILEATTR3
     *
     * @mbggenerated Sun Aug 07 16:48:26 CST 2016
     */
    public void setFileattr3(String fileattr3) {
        this.fileattr3 = fileattr3 == null ? null : fileattr3.trim();
    }

	@Override
	public String toString() {
		return "File [fileId=" + fileId + ", rcId=" + rcId + ", fileName="
				+ fileName + ", ifdigit=" + ifdigit + ", dataform=" + dataform
				+ ", fileUrl=" + fileUrl + ", volume=" + volume + ", unit="
				+ unit + ", ifarchive=" + ifarchive + ", fileType=" + fileType
				+ ", scale=" + scale + ", getId=" + getId + ", fileRemark="
				+ fileRemark + ", permissionClass=" + permissionClass
				+ ", creationdate=" + creationdate + ", coverageIds="
				+ coverageIds + ", coverage=" + coverage + ", year=" + year
				+ ", filedetailId=" + filedetailId + ", fileattr1=" + fileattr1
				+ ", fileattr2=" + fileattr2 + ", fileattr3=" + fileattr3 + "]";
	}
    
    
    
}