package com.fh.entity.amsmodel;

public class Hdm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Integer storageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.HD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String hdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.SERIANUM
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String serianum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.HD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String hdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.VOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String actvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.UNIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.HD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String hdLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.HD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String hdLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_hdm.HD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String hdRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.STORAGE_ID
     *
     * @return the value of ams_hdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Integer getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.STORAGE_ID
     *
     * @param storageId the value for ams_hdm.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setStorageId(Integer storageId) {
        this.storageId = storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.HD_ID
     *
     * @return the value of ams_hdm.HD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getHdId() {
        return hdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.HD_ID
     *
     * @param hdId the value for ams_hdm.HD_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setHdId(String hdId) {
        this.hdId = hdId == null ? null : hdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.SERIANUM
     *
     * @return the value of ams_hdm.SERIANUM
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getSerianum() {
        return serianum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.SERIANUM
     *
     * @param serianum the value for ams_hdm.SERIANUM
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setSerianum(String serianum) {
        this.serianum = serianum == null ? null : serianum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.HD_NAME
     *
     * @return the value of ams_hdm.HD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getHdName() {
        return hdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.HD_NAME
     *
     * @param hdName the value for ams_hdm.HD_NAME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setHdName(String hdName) {
        this.hdName = hdName == null ? null : hdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.VOLUME
     *
     * @return the value of ams_hdm.VOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.VOLUME
     *
     * @param volume the value for ams_hdm.VOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.ACTVOLUME
     *
     * @return the value of ams_hdm.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getActvolume() {
        return actvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.ACTVOLUME
     *
     * @param actvolume the value for ams_hdm.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setActvolume(String actvolume) {
        this.actvolume = actvolume == null ? null : actvolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.UNIT
     *
     * @return the value of ams_hdm.UNIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.UNIT
     *
     * @param unit the value for ams_hdm.UNIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.HD_LOCATION
     *
     * @return the value of ams_hdm.HD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getHdLocation() {
        return hdLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.HD_LOCATION
     *
     * @param hdLocation the value for ams_hdm.HD_LOCATION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setHdLocation(String hdLocation) {
        this.hdLocation = hdLocation == null ? null : hdLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.HD_LIMIT
     *
     * @return the value of ams_hdm.HD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getHdLimit() {
        return hdLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.HD_LIMIT
     *
     * @param hdLimit the value for ams_hdm.HD_LIMIT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setHdLimit(String hdLimit) {
        this.hdLimit = hdLimit == null ? null : hdLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_hdm.HD_REMARK
     *
     * @return the value of ams_hdm.HD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getHdRemark() {
        return hdRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_hdm.HD_REMARK
     *
     * @param hdRemark the value for ams_hdm.HD_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setHdRemark(String hdRemark) {
        this.hdRemark = hdRemark == null ? null : hdRemark.trim();
    }
}