package com.fh.entity.amsmodel;

import java.util.Date;

public class KmsData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.KDATA_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Integer kdataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.PRJ_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.PRJ_NAME_INPUT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String prjNameInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.CEQUNAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String cequname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.TYPE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.KDATA_URL
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String kdataUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.KDATA_LIMIT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String kdataLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.STORAGETYPE
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String storagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.REALSTORAGE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Integer realstorageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.KDATA_NAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String kdataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.CREATETIME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.MIJI
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String miji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.DATAFORM
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String dataform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.VOLUME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.UNIT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.KDATA_NUM
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String kdataNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.MULU
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String mulu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.REMARK
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.KDATA_TYPE_INPUT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String kdataTypeInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.COPY
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String copy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_data.IFEXIST
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Boolean ifexist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.KDATA_ID
     *
     * @return the value of kms_data.KDATA_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Integer getKdataId() {
        return kdataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.KDATA_ID
     *
     * @param kdataId the value for kms_data.KDATA_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setKdataId(Integer kdataId) {
        this.kdataId = kdataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.PRJ_ID
     *
     * @return the value of kms_data.PRJ_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.PRJ_ID
     *
     * @param prjId the value for kms_data.PRJ_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.PRJ_NAME_INPUT
     *
     * @return the value of kms_data.PRJ_NAME_INPUT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getPrjNameInput() {
        return prjNameInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.PRJ_NAME_INPUT
     *
     * @param prjNameInput the value for kms_data.PRJ_NAME_INPUT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setPrjNameInput(String prjNameInput) {
        this.prjNameInput = prjNameInput == null ? null : prjNameInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.CEQUNAME
     *
     * @return the value of kms_data.CEQUNAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getCequname() {
        return cequname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.CEQUNAME
     *
     * @param cequname the value for kms_data.CEQUNAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setCequname(String cequname) {
        this.cequname = cequname == null ? null : cequname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.TYPE_ID
     *
     * @return the value of kms_data.TYPE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.TYPE_ID
     *
     * @param typeId the value for kms_data.TYPE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.KDATA_URL
     *
     * @return the value of kms_data.KDATA_URL
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getKdataUrl() {
        return kdataUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.KDATA_URL
     *
     * @param kdataUrl the value for kms_data.KDATA_URL
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setKdataUrl(String kdataUrl) {
        this.kdataUrl = kdataUrl == null ? null : kdataUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.KDATA_LIMIT
     *
     * @return the value of kms_data.KDATA_LIMIT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getKdataLimit() {
        return kdataLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.KDATA_LIMIT
     *
     * @param kdataLimit the value for kms_data.KDATA_LIMIT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setKdataLimit(String kdataLimit) {
        this.kdataLimit = kdataLimit == null ? null : kdataLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.STORAGETYPE
     *
     * @return the value of kms_data.STORAGETYPE
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getStoragetype() {
        return storagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.STORAGETYPE
     *
     * @param storagetype the value for kms_data.STORAGETYPE
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setStoragetype(String storagetype) {
        this.storagetype = storagetype == null ? null : storagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.REALSTORAGE_ID
     *
     * @return the value of kms_data.REALSTORAGE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Integer getRealstorageId() {
        return realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.REALSTORAGE_ID
     *
     * @param realstorageId the value for kms_data.REALSTORAGE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setRealstorageId(Integer realstorageId) {
        this.realstorageId = realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.KDATA_NAME
     *
     * @return the value of kms_data.KDATA_NAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getKdataName() {
        return kdataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.KDATA_NAME
     *
     * @param kdataName the value for kms_data.KDATA_NAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setKdataName(String kdataName) {
        this.kdataName = kdataName == null ? null : kdataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.CREATETIME
     *
     * @return the value of kms_data.CREATETIME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.CREATETIME
     *
     * @param createtime the value for kms_data.CREATETIME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.MIJI
     *
     * @return the value of kms_data.MIJI
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getMiji() {
        return miji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.MIJI
     *
     * @param miji the value for kms_data.MIJI
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setMiji(String miji) {
        this.miji = miji == null ? null : miji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.DATAFORM
     *
     * @return the value of kms_data.DATAFORM
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getDataform() {
        return dataform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.DATAFORM
     *
     * @param dataform the value for kms_data.DATAFORM
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setDataform(String dataform) {
        this.dataform = dataform == null ? null : dataform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.VOLUME
     *
     * @return the value of kms_data.VOLUME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.VOLUME
     *
     * @param volume the value for kms_data.VOLUME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.UNIT
     *
     * @return the value of kms_data.UNIT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.UNIT
     *
     * @param unit the value for kms_data.UNIT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.KDATA_NUM
     *
     * @return the value of kms_data.KDATA_NUM
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getKdataNum() {
        return kdataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.KDATA_NUM
     *
     * @param kdataNum the value for kms_data.KDATA_NUM
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setKdataNum(String kdataNum) {
        this.kdataNum = kdataNum == null ? null : kdataNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.MULU
     *
     * @return the value of kms_data.MULU
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getMulu() {
        return mulu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.MULU
     *
     * @param mulu the value for kms_data.MULU
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setMulu(String mulu) {
        this.mulu = mulu == null ? null : mulu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.REMARK
     *
     * @return the value of kms_data.REMARK
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.REMARK
     *
     * @param remark the value for kms_data.REMARK
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.KDATA_TYPE_INPUT
     *
     * @return the value of kms_data.KDATA_TYPE_INPUT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getKdataTypeInput() {
        return kdataTypeInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.KDATA_TYPE_INPUT
     *
     * @param kdataTypeInput the value for kms_data.KDATA_TYPE_INPUT
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setKdataTypeInput(String kdataTypeInput) {
        this.kdataTypeInput = kdataTypeInput == null ? null : kdataTypeInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.COPY
     *
     * @return the value of kms_data.COPY
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getCopy() {
        return copy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.COPY
     *
     * @param copy the value for kms_data.COPY
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setCopy(String copy) {
        this.copy = copy == null ? null : copy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_data.IFEXIST
     *
     * @return the value of kms_data.IFEXIST
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Boolean getIfexist() {
        return ifexist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_data.IFEXIST
     *
     * @param ifexist the value for kms_data.IFEXIST
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setIfexist(Boolean ifexist) {
        this.ifexist = ifexist;
    }
}