package com.fh.entity.amsmodel;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class KmsFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.KFILE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private Integer kfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.PRJ_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.PRJ_NAME_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String prjNameInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.CEQUNAME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String cequname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.KFILE_NUM
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String kfileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.KFILE_NAME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String kfileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.CREATETIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.PAGE
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private Integer page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.KFILE_LIMIT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String kfileLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.STORAGEPLACE
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String storageplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.MIJI
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String miji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.MULU
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String mulu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.REMARK
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.REALSTORAGE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private Integer realstorageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.IFEXIST
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private Boolean ifexist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.COPYSTATUS
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String copystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.JIESHOUREN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String jieshourenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.BUMEN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String bumenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.YIJIAOREN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String yijiaorenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.YJBUMEN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String yjbumenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.JIESHOU_TIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date jieshouTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.YIJIAO_TIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date yijiaoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.TYPE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_file.KFBOXID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    private String kfboxid;

    
    
    
    
    private List<KmsAddFile> kmsAddFiles;

	public List<KmsAddFile> getKmsAddFiles() {
		return kmsAddFiles;
	}

	public void setKmsAddFiles(List<KmsAddFile> kmsAddFiles) {
		this.kmsAddFiles = kmsAddFiles;
	}
    
    
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.KFILE_ID
     *
     * @return the value of kms_file.KFILE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Integer getKfileId() {
        return kfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.KFILE_ID
     *
     * @param kfileId the value for kms_file.KFILE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setKfileId(Integer kfileId) {
        this.kfileId = kfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.PRJ_ID
     *
     * @return the value of kms_file.PRJ_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.PRJ_ID
     *
     * @param prjId the value for kms_file.PRJ_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.PRJ_NAME_INPUT
     *
     * @return the value of kms_file.PRJ_NAME_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getPrjNameInput() {
        return prjNameInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.PRJ_NAME_INPUT
     *
     * @param prjNameInput the value for kms_file.PRJ_NAME_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setPrjNameInput(String prjNameInput) {
        this.prjNameInput = prjNameInput == null ? null : prjNameInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.CEQUNAME
     *
     * @return the value of kms_file.CEQUNAME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getCequname() {
        return cequname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.CEQUNAME
     *
     * @param cequname the value for kms_file.CEQUNAME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setCequname(String cequname) {
        this.cequname = cequname == null ? null : cequname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.KFILE_NUM
     *
     * @return the value of kms_file.KFILE_NUM
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getKfileNum() {
        return kfileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.KFILE_NUM
     *
     * @param kfileNum the value for kms_file.KFILE_NUM
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setKfileNum(String kfileNum) {
        this.kfileNum = kfileNum == null ? null : kfileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.KFILE_NAME
     *
     * @return the value of kms_file.KFILE_NAME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getKfileName() {
        return kfileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.KFILE_NAME
     *
     * @param kfileName the value for kms_file.KFILE_NAME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setKfileName(String kfileName) {
        this.kfileName = kfileName == null ? null : kfileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.CREATETIME
     *
     * @return the value of kms_file.CREATETIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.CREATETIME
     *
     * @param createtime the value for kms_file.CREATETIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.PAGE
     *
     * @return the value of kms_file.PAGE
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.PAGE
     *
     * @param page the value for kms_file.PAGE
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.KFILE_LIMIT
     *
     * @return the value of kms_file.KFILE_LIMIT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getKfileLimit() {
        return kfileLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.KFILE_LIMIT
     *
     * @param kfileLimit the value for kms_file.KFILE_LIMIT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setKfileLimit(String kfileLimit) {
        this.kfileLimit = kfileLimit == null ? null : kfileLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.STORAGEPLACE
     *
     * @return the value of kms_file.STORAGEPLACE
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getStorageplace() {
        return storageplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.STORAGEPLACE
     *
     * @param storageplace the value for kms_file.STORAGEPLACE
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setStorageplace(String storageplace) {
        this.storageplace = storageplace == null ? null : storageplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.MIJI
     *
     * @return the value of kms_file.MIJI
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getMiji() {
        return miji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.MIJI
     *
     * @param miji the value for kms_file.MIJI
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setMiji(String miji) {
        this.miji = miji == null ? null : miji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.MULU
     *
     * @return the value of kms_file.MULU
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getMulu() {
        return mulu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.MULU
     *
     * @param mulu the value for kms_file.MULU
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setMulu(String mulu) {
        this.mulu = mulu == null ? null : mulu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.REMARK
     *
     * @return the value of kms_file.REMARK
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.REMARK
     *
     * @param remark the value for kms_file.REMARK
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.REALSTORAGE_ID
     *
     * @return the value of kms_file.REALSTORAGE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Integer getRealstorageId() {
        return realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.REALSTORAGE_ID
     *
     * @param realstorageId the value for kms_file.REALSTORAGE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setRealstorageId(Integer realstorageId) {
        this.realstorageId = realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.IFEXIST
     *
     * @return the value of kms_file.IFEXIST
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Boolean getIfexist() {
        return ifexist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.IFEXIST
     *
     * @param ifexist the value for kms_file.IFEXIST
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setIfexist(Boolean ifexist) {
        this.ifexist = ifexist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.COPYSTATUS
     *
     * @return the value of kms_file.COPYSTATUS
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getCopystatus() {
        return copystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.COPYSTATUS
     *
     * @param copystatus the value for kms_file.COPYSTATUS
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setCopystatus(String copystatus) {
        this.copystatus = copystatus == null ? null : copystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.JIESHOUREN_INPUT
     *
     * @return the value of kms_file.JIESHOUREN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getJieshourenInput() {
        return jieshourenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.JIESHOUREN_INPUT
     *
     * @param jieshourenInput the value for kms_file.JIESHOUREN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setJieshourenInput(String jieshourenInput) {
        this.jieshourenInput = jieshourenInput == null ? null : jieshourenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.BUMEN_INPUT
     *
     * @return the value of kms_file.BUMEN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getBumenInput() {
        return bumenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.BUMEN_INPUT
     *
     * @param bumenInput the value for kms_file.BUMEN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setBumenInput(String bumenInput) {
        this.bumenInput = bumenInput == null ? null : bumenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.YIJIAOREN_INPUT
     *
     * @return the value of kms_file.YIJIAOREN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getYijiaorenInput() {
        return yijiaorenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.YIJIAOREN_INPUT
     *
     * @param yijiaorenInput the value for kms_file.YIJIAOREN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setYijiaorenInput(String yijiaorenInput) {
        this.yijiaorenInput = yijiaorenInput == null ? null : yijiaorenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.YJBUMEN_INPUT
     *
     * @return the value of kms_file.YJBUMEN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getYjbumenInput() {
        return yjbumenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.YJBUMEN_INPUT
     *
     * @param yjbumenInput the value for kms_file.YJBUMEN_INPUT
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setYjbumenInput(String yjbumenInput) {
        this.yjbumenInput = yjbumenInput == null ? null : yjbumenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.JIESHOU_TIME
     *
     * @return the value of kms_file.JIESHOU_TIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Date getJieshouTime() {
        return jieshouTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.JIESHOU_TIME
     *
     * @param jieshouTime the value for kms_file.JIESHOU_TIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setJieshouTime(Date jieshouTime) {
        this.jieshouTime = jieshouTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.YIJIAO_TIME
     *
     * @return the value of kms_file.YIJIAO_TIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Date getYijiaoTime() {
        return yijiaoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.YIJIAO_TIME
     *
     * @param yijiaoTime the value for kms_file.YIJIAO_TIME
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setYijiaoTime(Date yijiaoTime) {
        this.yijiaoTime = yijiaoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.TYPE_ID
     *
     * @return the value of kms_file.TYPE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.TYPE_ID
     *
     * @param typeId the value for kms_file.TYPE_ID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_file.KFBOXID
     *
     * @return the value of kms_file.KFBOXID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public String getKfboxid() {
        return kfboxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_file.KFBOXID
     *
     * @param kfboxid the value for kms_file.KFBOXID
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    public void setKfboxid(String kfboxid) {
        this.kfboxid = kfboxid;
    }
}