package com.fh.entity.amsmodel;

import java.util.Date;
import java.util.List;

import com.fh.entity.fms.FmsDocBox;

public class KmsFileBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.ID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.PID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.KBOXNAME
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String kboxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.STH
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String sth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.REMARK
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.WHO
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String who;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.HOW
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String how;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.WHEN
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private Date fwhen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.WHERE
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String fwhere;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.STORAGEID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private Integer storageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_filebox.KBOXABOUT
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    private String kboxabout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.ID
     *
     * @return the value of kms_filebox.ID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    
    
    
	//added for ztree
	private Boolean open;
    private Boolean isParent=true;
    private List<KmsFileBox>  children;
    private String url;
    private String target ;
    
	public Boolean getOpen() {
		return open;
	}
	public void setOpen(Boolean open) {
		this.open = open;
	}
	public Boolean getIsParent() {
		return isParent;
	}

	public void setIsParent(Boolean isParent) {
		this.isParent = isParent;
	}
	public List<KmsFileBox> getChildren() {
		return children;
	}
	public void setChildren(List<KmsFileBox> children) {
		this.children = children;
	}
	
	public String getTarget() {
		return "treeFrame";
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUrl() {
		return "kms/listkfile.do?pid="+id;
	}
    
	public Boolean getDrag() {
		return true;
	}


    
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.ID
     *
     * @param id the value for kms_filebox.ID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.PID
     *
     * @return the value of kms_filebox.PID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.PID
     *
     * @param pid the value for kms_filebox.PID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.KBOXNAME
     *
     * @return the value of kms_filebox.KBOXNAME
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getKboxname() {
        return kboxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.KBOXNAME
     *
     * @param kboxname the value for kms_filebox.KBOXNAME
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setKboxname(String kboxname) {
        this.kboxname = kboxname == null ? null : kboxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.STH
     *
     * @return the value of kms_filebox.STH
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getSth() {
        return sth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.STH
     *
     * @param sth the value for kms_filebox.STH
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setSth(String sth) {
        this.sth = sth == null ? null : sth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.REMARK
     *
     * @return the value of kms_filebox.REMARK
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.REMARK
     *
     * @param remark the value for kms_filebox.REMARK
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.WHO
     *
     * @return the value of kms_filebox.WHO
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getWho() {
        return who;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.WHO
     *
     * @param who the value for kms_filebox.WHO
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setWho(String who) {
        this.who = who == null ? null : who.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.HOW
     *
     * @return the value of kms_filebox.HOW
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getHow() {
        return how;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.HOW
     *
     * @param how the value for kms_filebox.HOW
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setHow(String how) {
        this.how = how == null ? null : how.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.WHEN
     *
     * @return the value of kms_filebox.WHEN
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public Date getFwhen() {
        return fwhen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.WHEN
     *
     * @param when the value for kms_filebox.WHEN
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setFwhen(Date fwhen) {
        this.fwhen = fwhen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.WHERE
     *
     * @return the value of kms_filebox.WHERE
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getFwhere() {
        return fwhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.WHERE
     *
     * @param where the value for kms_filebox.WHERE
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setFwhere(String fwhere) {
        this.fwhere = fwhere == null ? null : fwhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.STORAGEID
     *
     * @return the value of kms_filebox.STORAGEID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public Integer getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.STORAGEID
     *
     * @param storageid the value for kms_filebox.STORAGEID
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setStorageid(Integer storageid) {
        this.storageid = storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_filebox.KBOXABOUT
     *
     * @return the value of kms_filebox.KBOXABOUT
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public String getKboxabout() {
        return kboxabout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_filebox.KBOXABOUT
     *
     * @param kboxabout the value for kms_filebox.KBOXABOUT
     *
     * @mbggenerated Tue Sep 19 10:23:13 CST 2017
     */
    public void setKboxabout(String kboxabout) {
        this.kboxabout = kboxabout == null ? null : kboxabout.trim();
    }
}