package com.fh.entity.amsmodel;

import java.util.Date;

public class KmsFiles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.KFILES_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer kfilesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.PRJ_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.PRJ_NAME_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String prjNameInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.CEQUNAME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String cequname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.LE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer le;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.KFILES_BOX_NUM
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String kfilesBoxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.KFILES_BOX_NAME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String kfilesBoxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.CREATETIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.LFT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer lft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.RT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer rt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.PAGE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.KFILES_LIMIT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String kfilesLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.STORAGEPLACE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String storageplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.KFILES_NUM
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String kfilesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.MIJI
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String miji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.MULU
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String mulu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.REMARK
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.REALSTORAGE_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer realstorageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.IFEXIST
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Boolean ifexist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.COPY
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String copy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.JIESHOUREN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String jieshourenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.BUMEN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String bumenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.YIJIAOREN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String yijiaorenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.YJBUMEN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private String yjbumenInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.JIESHOU_TIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Date jieshouTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.YIJIAO_TIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Date yijiaoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_files.TYPE_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    private Integer typeId;
    
    
    /*2017年8月31日12:04:46*/
    private Boolean isParent=true;
	public Boolean getIsParent() {
		return isParent;
	}
	public void setIsParent(Boolean isParent) {
		this.isParent = isParent;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.KFILES_ID
     *
     * @return the value of kms_files.KFILES_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getKfilesId() {
        return kfilesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.KFILES_ID
     *
     * @param kfilesId the value for kms_files.KFILES_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setKfilesId(Integer kfilesId) {
        this.kfilesId = kfilesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.PRJ_ID
     *
     * @return the value of kms_files.PRJ_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.PRJ_ID
     *
     * @param prjId the value for kms_files.PRJ_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.PRJ_NAME_INPUT
     *
     * @return the value of kms_files.PRJ_NAME_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getPrjNameInput() {
        return prjNameInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.PRJ_NAME_INPUT
     *
     * @param prjNameInput the value for kms_files.PRJ_NAME_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setPrjNameInput(String prjNameInput) {
        this.prjNameInput = prjNameInput == null ? null : prjNameInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.CEQUNAME
     *
     * @return the value of kms_files.CEQUNAME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getCequname() {
        return cequname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.CEQUNAME
     *
     * @param cequname the value for kms_files.CEQUNAME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setCequname(String cequname) {
        this.cequname = cequname == null ? null : cequname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.LE
     *
     * @return the value of kms_files.LE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getLe() {
        return le;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.LE
     *
     * @param le the value for kms_files.LE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setLe(Integer le) {
        this.le = le;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.KFILES_BOX_NUM
     *
     * @return the value of kms_files.KFILES_BOX_NUM
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getKfilesBoxNum() {
        return kfilesBoxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.KFILES_BOX_NUM
     *
     * @param kfilesBoxNum the value for kms_files.KFILES_BOX_NUM
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setKfilesBoxNum(String kfilesBoxNum) {
        this.kfilesBoxNum = kfilesBoxNum == null ? null : kfilesBoxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.KFILES_BOX_NAME
     *
     * @return the value of kms_files.KFILES_BOX_NAME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getKfilesBoxName() {
        return kfilesBoxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.KFILES_BOX_NAME
     *
     * @param kfilesBoxName the value for kms_files.KFILES_BOX_NAME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setKfilesBoxName(String kfilesBoxName) {
        this.kfilesBoxName = kfilesBoxName == null ? null : kfilesBoxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.CREATETIME
     *
     * @return the value of kms_files.CREATETIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.CREATETIME
     *
     * @param createtime the value for kms_files.CREATETIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.LFT
     *
     * @return the value of kms_files.LFT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getLft() {
        return lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.LFT
     *
     * @param lft the value for kms_files.LFT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setLft(Integer lft) {
        this.lft = lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.RT
     *
     * @return the value of kms_files.RT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getRt() {
        return rt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.RT
     *
     * @param rt the value for kms_files.RT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setRt(Integer rt) {
        this.rt = rt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.PAGE
     *
     * @return the value of kms_files.PAGE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.PAGE
     *
     * @param page the value for kms_files.PAGE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.KFILES_LIMIT
     *
     * @return the value of kms_files.KFILES_LIMIT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getKfilesLimit() {
        return kfilesLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.KFILES_LIMIT
     *
     * @param kfilesLimit the value for kms_files.KFILES_LIMIT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setKfilesLimit(String kfilesLimit) {
        this.kfilesLimit = kfilesLimit == null ? null : kfilesLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.STORAGEPLACE
     *
     * @return the value of kms_files.STORAGEPLACE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getStorageplace() {
        return storageplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.STORAGEPLACE
     *
     * @param storageplace the value for kms_files.STORAGEPLACE
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setStorageplace(String storageplace) {
        this.storageplace = storageplace == null ? null : storageplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.KFILES_NUM
     *
     * @return the value of kms_files.KFILES_NUM
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getKfilesNum() {
        return kfilesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.KFILES_NUM
     *
     * @param kfilesNum the value for kms_files.KFILES_NUM
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setKfilesNum(String kfilesNum) {
        this.kfilesNum = kfilesNum == null ? null : kfilesNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.MIJI
     *
     * @return the value of kms_files.MIJI
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getMiji() {
        return miji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.MIJI
     *
     * @param miji the value for kms_files.MIJI
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setMiji(String miji) {
        this.miji = miji == null ? null : miji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.MULU
     *
     * @return the value of kms_files.MULU
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getMulu() {
        return mulu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.MULU
     *
     * @param mulu the value for kms_files.MULU
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setMulu(String mulu) {
        this.mulu = mulu == null ? null : mulu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.REMARK
     *
     * @return the value of kms_files.REMARK
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.REMARK
     *
     * @param remark the value for kms_files.REMARK
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.REALSTORAGE_ID
     *
     * @return the value of kms_files.REALSTORAGE_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getRealstorageId() {
        return realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.REALSTORAGE_ID
     *
     * @param realstorageId the value for kms_files.REALSTORAGE_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setRealstorageId(Integer realstorageId) {
        this.realstorageId = realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.IFEXIST
     *
     * @return the value of kms_files.IFEXIST
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Boolean getIfexist() {
        return ifexist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.IFEXIST
     *
     * @param ifexist the value for kms_files.IFEXIST
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setIfexist(Boolean ifexist) {
        this.ifexist = ifexist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.COPY
     *
     * @return the value of kms_files.COPY
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getCopy() {
        return copy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.COPY
     *
     * @param copy the value for kms_files.COPY
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setCopy(String copy) {
        this.copy = copy == null ? null : copy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.JIESHOUREN_INPUT
     *
     * @return the value of kms_files.JIESHOUREN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getJieshourenInput() {
        return jieshourenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.JIESHOUREN_INPUT
     *
     * @param jieshourenInput the value for kms_files.JIESHOUREN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setJieshourenInput(String jieshourenInput) {
        this.jieshourenInput = jieshourenInput == null ? null : jieshourenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.BUMEN_INPUT
     *
     * @return the value of kms_files.BUMEN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getBumenInput() {
        return bumenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.BUMEN_INPUT
     *
     * @param bumenInput the value for kms_files.BUMEN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setBumenInput(String bumenInput) {
        this.bumenInput = bumenInput == null ? null : bumenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.YIJIAOREN_INPUT
     *
     * @return the value of kms_files.YIJIAOREN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getYijiaorenInput() {
        return yijiaorenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.YIJIAOREN_INPUT
     *
     * @param yijiaorenInput the value for kms_files.YIJIAOREN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setYijiaorenInput(String yijiaorenInput) {
        this.yijiaorenInput = yijiaorenInput == null ? null : yijiaorenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.YJBUMEN_INPUT
     *
     * @return the value of kms_files.YJBUMEN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public String getYjbumenInput() {
        return yjbumenInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.YJBUMEN_INPUT
     *
     * @param yjbumenInput the value for kms_files.YJBUMEN_INPUT
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setYjbumenInput(String yjbumenInput) {
        this.yjbumenInput = yjbumenInput == null ? null : yjbumenInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.JIESHOU_TIME
     *
     * @return the value of kms_files.JIESHOU_TIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Date getJieshouTime() {
        return jieshouTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.JIESHOU_TIME
     *
     * @param jieshouTime the value for kms_files.JIESHOU_TIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setJieshouTime(Date jieshouTime) {
        this.jieshouTime = jieshouTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.YIJIAO_TIME
     *
     * @return the value of kms_files.YIJIAO_TIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Date getYijiaoTime() {
        return yijiaoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.YIJIAO_TIME
     *
     * @param yijiaoTime the value for kms_files.YIJIAO_TIME
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setYijiaoTime(Date yijiaoTime) {
        this.yijiaoTime = yijiaoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_files.TYPE_ID
     *
     * @return the value of kms_files.TYPE_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_files.TYPE_ID
     *
     * @param typeId the value for kms_files.TYPE_ID
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}