package com.fh.entity.amsmodel;

public class KmsOperateType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_operate_type.OP_TYPE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private Integer opTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_operate_type.OP_TYPE_NAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String opTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_operate_type.REMARK
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_operate_type.OP_TYPE_ID
     *
     * @return the value of kms_operate_type.OP_TYPE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public Integer getOpTypeId() {
        return opTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_operate_type.OP_TYPE_ID
     *
     * @param opTypeId the value for kms_operate_type.OP_TYPE_ID
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setOpTypeId(Integer opTypeId) {
        this.opTypeId = opTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_operate_type.OP_TYPE_NAME
     *
     * @return the value of kms_operate_type.OP_TYPE_NAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getOpTypeName() {
        return opTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_operate_type.OP_TYPE_NAME
     *
     * @param opTypeName the value for kms_operate_type.OP_TYPE_NAME
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setOpTypeName(String opTypeName) {
        this.opTypeName = opTypeName == null ? null : opTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_operate_type.REMARK
     *
     * @return the value of kms_operate_type.REMARK
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_operate_type.REMARK
     *
     * @param remark the value for kms_operate_type.REMARK
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}