package com.fh.entity.amsmodel;

public class KmsSendContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.XUHAO
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer xuhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.KFILE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String kfileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.FEN
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer fen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.CE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer ce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.ZHANG
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer zhang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.DIAN
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer dian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kms_sendcontent.BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.ID
     *
     * @return the value of kms_sendcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.ID
     *
     * @param id the value for kms_sendcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.XUHAO
     *
     * @return the value of kms_sendcontent.XUHAO
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getXuhao() {
        return xuhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.XUHAO
     *
     * @param xuhao the value for kms_sendcontent.XUHAO
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setXuhao(Integer xuhao) {
        this.xuhao = xuhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.KFILE_NAME
     *
     * @return the value of kms_sendcontent.KFILE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getKfileName() {
        return kfileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.KFILE_NAME
     *
     * @param kfileName the value for kms_sendcontent.KFILE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setKfileName(String kfileName) {
        this.kfileName = kfileName == null ? null : kfileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.FEN
     *
     * @return the value of kms_sendcontent.FEN
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getFen() {
        return fen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.FEN
     *
     * @param fen the value for kms_sendcontent.FEN
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setFen(Integer fen) {
        this.fen = fen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.CE
     *
     * @return the value of kms_sendcontent.CE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getCe() {
        return ce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.CE
     *
     * @param ce the value for kms_sendcontent.CE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setCe(Integer ce) {
        this.ce = ce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.ZHANG
     *
     * @return the value of kms_sendcontent.ZHANG
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getZhang() {
        return zhang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.ZHANG
     *
     * @param zhang the value for kms_sendcontent.ZHANG
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setZhang(Integer zhang) {
        this.zhang = zhang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.DIAN
     *
     * @return the value of kms_sendcontent.DIAN
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getDian() {
        return dian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.DIAN
     *
     * @param dian the value for kms_sendcontent.DIAN
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDian(Integer dian) {
        this.dian = dian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kms_sendcontent.BZ
     *
     * @return the value of kms_sendcontent.BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kms_sendcontent.BZ
     *
     * @param bz the value for kms_sendcontent.BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}