package com.fh.entity.amsmodel;

public class PmsBorrowContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_borrowcontent.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pmsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_borrowcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String borrowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_borrowcontent.fms_ID
     *
     * @return the value of fms_borrowcontent.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPmsId() {
        return pmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_borrowcontent.fms_ID
     *
     * @param fmsId the value for fms_borrowcontent.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPmsId(String pmsId) {
        this.pmsId = pmsId == null ? null : pmsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_borrowcontent.ID
     *
     * @return the value of fms_borrowcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_borrowcontent.ID
     *
     * @param id the value for fms_borrowcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setBorrowId(String id) {
        this.borrowId = id == null ? null : id.trim();
    }
}