package com.fh.entity.amsmodel;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class PmsCertificateAndHonor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.PRYZS_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pryzsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.P_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.PRYZS_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pryzsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.PRYZS_TIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date pryzsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.PRYZS_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pryzsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.PRYZS_ORGNIZATION
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pryzsOrgnization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_certificateandhonor.PRYZS_BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pryzsBz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.PRYZS_ID
     *
     * @return the value of pms_certificateandhonor.PRYZS_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPryzsId() {
        return pryzsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.PRYZS_ID
     *
     * @param pryzsId the value for pms_certificateandhonor.PRYZS_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPryzsId(String pryzsId) {
        this.pryzsId = pryzsId == null ? null : pryzsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.P_ID
     *
     * @return the value of pms_certificateandhonor.P_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.P_ID
     *
     * @param pId the value for pms_certificateandhonor.P_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.PRYZS_NAME
     *
     * @return the value of pms_certificateandhonor.PRYZS_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPryzsName() {
        return pryzsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.PRYZS_NAME
     *
     * @param pryzsName the value for pms_certificateandhonor.PRYZS_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPryzsName(String pryzsName) {
        this.pryzsName = pryzsName == null ? null : pryzsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.PRYZS_TIME
     *
     * @return the value of pms_certificateandhonor.PRYZS_TIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getPryzsTime() {
        return pryzsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.PRYZS_TIME
     *
     * @param pryzsTime the value for pms_certificateandhonor.PRYZS_TIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPryzsTime(Date pryzsTime) {
        this.pryzsTime = pryzsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.PRYZS_NUM
     *
     * @return the value of pms_certificateandhonor.PRYZS_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPryzsNum() {
        return pryzsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.PRYZS_NUM
     *
     * @param pryzsNum the value for pms_certificateandhonor.PRYZS_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPryzsNum(String pryzsNum) {
        this.pryzsNum = pryzsNum == null ? null : pryzsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.PRYZS_ORGNIZATION
     *
     * @return the value of pms_certificateandhonor.PRYZS_ORGNIZATION
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPryzsOrgnization() {
        return pryzsOrgnization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.PRYZS_ORGNIZATION
     *
     * @param pryzsOrgnization the value for pms_certificateandhonor.PRYZS_ORGNIZATION
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPryzsOrgnization(String pryzsOrgnization) {
        this.pryzsOrgnization = pryzsOrgnization == null ? null : pryzsOrgnization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_certificateandhonor.PRYZS_BZ
     *
     * @return the value of pms_certificateandhonor.PRYZS_BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPryzsBz() {
        return pryzsBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_certificateandhonor.PRYZS_BZ
     *
     * @param pryzsBz the value for pms_certificateandhonor.PRYZS_BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPryzsBz(String pryzsBz) {
        this.pryzsBz = pryzsBz == null ? null : pryzsBz.trim();
    }
}