package com.fh.entity.amsmodel;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class PmsDocMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.P_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pId;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.pms_PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pmsPfileId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_CREATIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date pfileCreatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_PAGES
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer pfilePages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_LOADTIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date pfileLoadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.EXISTORNOT
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer existornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.RECEIVE_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String receiveHow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.RECEIVE_DATE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date receiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.REMOVE_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String removeHow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.REMOVE_DATE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date removeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.OTHER
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_docmain.PFILE_TYPE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileTypeId;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_ID
     *
     * @return the value of pms_docmain.PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileId() {
        return pfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_ID
     *
     * @param pfileId the value for pms_docmain.PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileId(String pfileId) {
        this.pfileId = pfileId == null ? null : pfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.P_ID
     *
     * @return the value of pms_docmain.P_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.P_ID
     *
     * @param pId the value for pms_docmain.P_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.pms_PFILE_ID
     *
     * @return the value of pms_docmain.pms_PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPmsPfileId() {
        return pmsPfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.pms_PFILE_ID
     *
     * @param pmsPfileId the value for pms_docmain.pms_PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPmsPfileId(String pmsPfileId) {
        this.pmsPfileId = pmsPfileId == null ? null : pmsPfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_NUM
     *
     * @return the value of pms_docmain.PFILE_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileNum() {
        return pfileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_NUM
     *
     * @param pfileNum the value for pms_docmain.PFILE_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileNum(String pfileNum) {
        this.pfileNum = pfileNum == null ? null : pfileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_NAME
     *
     * @return the value of pms_docmain.PFILE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileName() {
        return pfileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_NAME
     *
     * @param pfileName the value for pms_docmain.PFILE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileName(String pfileName) {
        this.pfileName = pfileName == null ? null : pfileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_CREATIME
     *
     * @return the value of pms_docmain.PFILE_CREATIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getPfileCreatime() {
        return pfileCreatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_CREATIME
     *
     * @param pfileCreatime the value for pms_docmain.PFILE_CREATIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileCreatime(Date pfileCreatime) {
        this.pfileCreatime = pfileCreatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_PAGES
     *
     * @return the value of pms_docmain.PFILE_PAGES
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getPfilePages() {
        return pfilePages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_PAGES
     *
     * @param pfilePages the value for pms_docmain.PFILE_PAGES
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfilePages(Integer pfilePages) {
        this.pfilePages = pfilePages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_REMARK
     *
     * @return the value of pms_docmain.PFILE_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileRemark() {
        return pfileRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_REMARK
     *
     * @param pfileRemark the value for pms_docmain.PFILE_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileRemark(String pfileRemark) {
        this.pfileRemark = pfileRemark == null ? null : pfileRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_LOADTIME
     *
     * @return the value of pms_docmain.PFILE_LOADTIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getPfileLoadtime() {
        return pfileLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_LOADTIME
     *
     * @param pfileLoadtime the value for pms_docmain.PFILE_LOADTIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileLoadtime(Date pfileLoadtime) {
        this.pfileLoadtime = pfileLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.EXISTORNOT
     *
     * @return the value of pms_docmain.EXISTORNOT
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getExistornot() {
        return existornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.EXISTORNOT
     *
     * @param existornot the value for pms_docmain.EXISTORNOT
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setExistornot(Integer existornot) {
        this.existornot = existornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.RECEIVE_HOW
     *
     * @return the value of pms_docmain.RECEIVE_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getReceiveHow() {
        return receiveHow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.RECEIVE_HOW
     *
     * @param receiveHow the value for pms_docmain.RECEIVE_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setReceiveHow(String receiveHow) {
        this.receiveHow = receiveHow == null ? null : receiveHow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.RECEIVE_DATE
     *
     * @return the value of pms_docmain.RECEIVE_DATE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getReceiveDate() {
        return receiveDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.PFILE_TYPE_ID
     *
     * @return the value of pms_docmain.PFILE_TYPE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileTypeId() {
		return pfileTypeId;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.RECEIVE_DATE
     *
     * @param receiveDate the value for pms_docmain.RECEIVE_DATE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.REMOVE_HOW
     *
     * @return the value of pms_docmain.REMOVE_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getRemoveHow() {
        return removeHow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.REMOVE_HOW
     *
     * @param removeHow the value for pms_docmain.REMOVE_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setRemoveHow(String removeHow) {
        this.removeHow = removeHow == null ? null : removeHow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.REMOVE_DATE
     *
     * @return the value of pms_docmain.REMOVE_DATE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getRemoveDate() {
        return removeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.REMOVE_DATE
     *
     * @param removeDate the value for pms_docmain.REMOVE_DATE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setRemoveDate(Date removeDate) {
        this.removeDate = removeDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_docmain.OTHER
     *
     * @return the value of pms_docmain.OTHER
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.OTHER
     *
     * @param other the value for pms_docmain.OTHER
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

 
	  /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_docmain.PFILE_TYPE_ID
     *
     * @param other the value for pms_docmain.PFILE_TYPE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
	public void setPfileTypeId(String pfileTypeId) {
		this.pfileTypeId = pfileTypeId== null ? null : pfileTypeId.trim();
	}
}