package com.fh.entity.amsmodel;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class PmsPExperience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.P_EX_ID
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    private String pExId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.P_ID
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.NAME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.STARTTIME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.ENDTIME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.PLACE
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.STH
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    private String sth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pexperience.BZ
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.P_EX_ID
     *
     * @return the value of pms_pexperience.P_EX_ID
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public String getpExId() {
        return pExId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.P_EX_ID
     *
     * @param pExId the value for pms_pexperience.P_EX_ID
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setpExId(String pExId) {
        this.pExId = pExId == null ? null : pExId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.P_ID
     *
     * @return the value of pms_pexperience.P_ID
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.P_ID
     *
     * @param pId the value for pms_pexperience.P_ID
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.NAME
     *
     * @return the value of pms_pexperience.NAME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.NAME
     *
     * @param name the value for pms_pexperience.NAME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.STARTTIME
     *
     * @return the value of pms_pexperience.STARTTIME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.STARTTIME
     *
     * @param starttime the value for pms_pexperience.STARTTIME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.ENDTIME
     *
     * @return the value of pms_pexperience.ENDTIME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.ENDTIME
     *
     * @param endtime the value for pms_pexperience.ENDTIME
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.PLACE
     *
     * @return the value of pms_pexperience.PLACE
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.PLACE
     *
     * @param place the value for pms_pexperience.PLACE
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.STH
     *
     * @return the value of pms_pexperience.STH
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public String getSth() {
        return sth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.STH
     *
     * @param sth the value for pms_pexperience.STH
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setSth(String sth) {
        this.sth = sth == null ? null : sth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pexperience.BZ
     *
     * @return the value of pms_pexperience.BZ
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pexperience.BZ
     *
     * @param bz the value for pms_pexperience.BZ
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}