package com.fh.entity.amsmodel;

public class PmsPFileType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pfiletype.PFILE_TYPE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pfiletype.PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pfiletype.PFILE_TYPE_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pfiletype.PFILE_TYPE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_pfiletype.PFILE_TYPE_BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String pfileTypeBz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pfiletype.PFILE_TYPE_ID
     *
     * @return the value of pms_pfiletype.PFILE_TYPE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileTypeId() {
        return pfileTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pfiletype.PFILE_TYPE_ID
     *
     * @param pfileTypeId the value for pms_pfiletype.PFILE_TYPE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileTypeId(String pfileTypeId) {
        this.pfileTypeId = pfileTypeId == null ? null : pfileTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pfiletype.PFILE_ID
     *
     * @return the value of pms_pfiletype.PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileId() {
        return pfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pfiletype.PFILE_ID
     *
     * @param pfileId the value for pms_pfiletype.PFILE_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileId(String pfileId) {
        this.pfileId = pfileId == null ? null : pfileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pfiletype.PFILE_TYPE_NUM
     *
     * @return the value of pms_pfiletype.PFILE_TYPE_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileTypeNum() {
        return pfileTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pfiletype.PFILE_TYPE_NUM
     *
     * @param pfileTypeNum the value for pms_pfiletype.PFILE_TYPE_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileTypeNum(String pfileTypeNum) {
        this.pfileTypeNum = pfileTypeNum == null ? null : pfileTypeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pfiletype.PFILE_TYPE_NAME
     *
     * @return the value of pms_pfiletype.PFILE_TYPE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileTypeName() {
        return pfileTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pfiletype.PFILE_TYPE_NAME
     *
     * @param pfileTypeName the value for pms_pfiletype.PFILE_TYPE_NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileTypeName(String pfileTypeName) {
        this.pfileTypeName = pfileTypeName == null ? null : pfileTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_pfiletype.PFILE_TYPE_BZ
     *
     * @return the value of pms_pfiletype.PFILE_TYPE_BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPfileTypeBz() {
        return pfileTypeBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_pfiletype.PFILE_TYPE_BZ
     *
     * @param pfileTypeBz the value for pms_pfiletype.PFILE_TYPE_BZ
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPfileTypeBz(String pfileTypeBz) {
        this.pfileTypeBz = pfileTypeBz == null ? null : pfileTypeBz.trim();
    }
}