package com.fh.entity.amsmodel;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.COVERAGE_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private Integer coverageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJTYPE
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_NAME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_ORIGIN
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_LEADER
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_DEPART
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_STRATTIME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private Date prjStrattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_ENDTIME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private Date prjEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_PROGRESS
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRJ_REMARK
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String prjRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.USER_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.YEAR
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.RECORD_LIMIT
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String recordLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.SECURITY_CLASS
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String securityClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_project.PRO_NUM
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    private String proNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_ID
     *
     * @return the value of ams_project.PRJ_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_ID
     *
     * @param prjId the value for ams_project.PRJ_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.COVERAGE_ID
     *
     * @return the value of ams_project.COVERAGE_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public Integer getCoverageId() {
        return coverageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.COVERAGE_ID
     *
     * @param coverageId the value for ams_project.COVERAGE_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setCoverageId(Integer coverageId) {
        this.coverageId = coverageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJTYPE
     *
     * @return the value of ams_project.PRJTYPE
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjtype() {
        return prjtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJTYPE
     *
     * @param prjtype the value for ams_project.PRJTYPE
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjtype(String prjtype) {
        this.prjtype = prjtype == null ? null : prjtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_NAME
     *
     * @return the value of ams_project.PRJ_NAME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjName() {
        return prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_NAME
     *
     * @param prjName the value for ams_project.PRJ_NAME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjName(String prjName) {
        this.prjName = prjName == null ? null : prjName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_ORIGIN
     *
     * @return the value of ams_project.PRJ_ORIGIN
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjOrigin() {
        return prjOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_ORIGIN
     *
     * @param prjOrigin the value for ams_project.PRJ_ORIGIN
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjOrigin(String prjOrigin) {
        this.prjOrigin = prjOrigin == null ? null : prjOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_LEADER
     *
     * @return the value of ams_project.PRJ_LEADER
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjLeader() {
        return prjLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_LEADER
     *
     * @param prjLeader the value for ams_project.PRJ_LEADER
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjLeader(String prjLeader) {
        this.prjLeader = prjLeader == null ? null : prjLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_DEPART
     *
     * @return the value of ams_project.PRJ_DEPART
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjDepart() {
        return prjDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_DEPART
     *
     * @param prjDepart the value for ams_project.PRJ_DEPART
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjDepart(String prjDepart) {
        this.prjDepart = prjDepart == null ? null : prjDepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_STRATTIME
     *
     * @return the value of ams_project.PRJ_STRATTIME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public Date getPrjStrattime() {
        return prjStrattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_STRATTIME
     *
     * @param prjStrattime the value for ams_project.PRJ_STRATTIME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjStrattime(Date prjStrattime) {
        this.prjStrattime = prjStrattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_ENDTIME
     *
     * @return the value of ams_project.PRJ_ENDTIME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public Date getPrjEndtime() {
        return prjEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_ENDTIME
     *
     * @param prjEndtime the value for ams_project.PRJ_ENDTIME
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjEndtime(Date prjEndtime) {
        this.prjEndtime = prjEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_PROGRESS
     *
     * @return the value of ams_project.PRJ_PROGRESS
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjProgress() {
        return prjProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_PROGRESS
     *
     * @param prjProgress the value for ams_project.PRJ_PROGRESS
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjProgress(String prjProgress) {
        this.prjProgress = prjProgress == null ? null : prjProgress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRJ_REMARK
     *
     * @return the value of ams_project.PRJ_REMARK
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getPrjRemark() {
        return prjRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRJ_REMARK
     *
     * @param prjRemark the value for ams_project.PRJ_REMARK
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setPrjRemark(String prjRemark) {
        this.prjRemark = prjRemark == null ? null : prjRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.USER_ID
     *
     * @return the value of ams_project.USER_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.USER_ID
     *
     * @param userId the value for ams_project.USER_ID
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.YEAR
     *
     * @return the value of ams_project.YEAR
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.YEAR
     *
     * @param year the value for ams_project.YEAR
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.RECORD_LIMIT
     *
     * @return the value of ams_project.RECORD_LIMIT
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getRecordLimit() {
        return recordLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.RECORD_LIMIT
     *
     * @param recordLimit the value for ams_project.RECORD_LIMIT
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setRecordLimit(String recordLimit) {
        this.recordLimit = recordLimit == null ? null : recordLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.SECURITY_CLASS
     *
     * @return the value of ams_project.SECURITY_CLASS
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getSecurityClass() {
        return securityClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.SECURITY_CLASS
     *
     * @param securityClass the value for ams_project.SECURITY_CLASS
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setSecurityClass(String securityClass) {
        this.securityClass = securityClass == null ? null : securityClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_project.PRO_NUM
     *
     * @return the value of ams_project.PRO_NUM
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public String getProNum() {
        return proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_project.PRO_NUM
     *
     * @param proNum the value for ams_project.PRO_NUM
     *
     * @mbggenerated Wed Aug 03 15:37:35 CST 2016
     */
    public void setProNum(String proNum) {
        this.proNum = proNum == null ? null : proNum.trim();
    }
}