package com.fh.entity.amsmodel;

public class RealStorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.REALSTORAGE_ID
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private Integer realstorageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.STORAGE_TYPENAME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String storageTypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.STORAGE_NAME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String storageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.STORAGE_TYPE
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String storageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.VOLUME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String actvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.UNIT
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.LOCATION
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.LIMIT
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.DELETETIME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String deletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.DELETEWHY
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String deletewhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.SERANUM
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String seranum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.FD_YEAR
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String fdYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.FD_S
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String fdS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.FD_G
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String fdG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.FD_PAGE
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String fdPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.STORAGE_REMARK
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String storageRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.OTHER1
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.OTHER2
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_realstorage.OTHER3
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    private String other3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.REALSTORAGE_ID
     *
     * @return the value of ams_realstorage.REALSTORAGE_ID
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public Integer getRealstorageId() {
        return realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.REALSTORAGE_ID
     *
     * @param realstorageId the value for ams_realstorage.REALSTORAGE_ID
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setRealstorageId(Integer realstorageId) {
        this.realstorageId = realstorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.STORAGE_TYPENAME
     *
     * @return the value of ams_realstorage.STORAGE_TYPENAME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getStorageTypename() {
        return storageTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.STORAGE_TYPENAME
     *
     * @param storageTypename the value for ams_realstorage.STORAGE_TYPENAME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setStorageTypename(String storageTypename) {
        this.storageTypename = storageTypename == null ? null : storageTypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.STORAGE_NAME
     *
     * @return the value of ams_realstorage.STORAGE_NAME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getStorageName() {
        return storageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.STORAGE_NAME
     *
     * @param storageName the value for ams_realstorage.STORAGE_NAME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setStorageName(String storageName) {
        this.storageName = storageName == null ? null : storageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.STORAGE_TYPE
     *
     * @return the value of ams_realstorage.STORAGE_TYPE
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.STORAGE_TYPE
     *
     * @param storageType the value for ams_realstorage.STORAGE_TYPE
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setStorageType(String storageType) {
        this.storageType = storageType == null ? null : storageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.VOLUME
     *
     * @return the value of ams_realstorage.VOLUME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.VOLUME
     *
     * @param volume the value for ams_realstorage.VOLUME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.ACTVOLUME
     *
     * @return the value of ams_realstorage.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getActvolume() {
        return actvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.ACTVOLUME
     *
     * @param actvolume the value for ams_realstorage.ACTVOLUME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setActvolume(String actvolume) {
        this.actvolume = actvolume == null ? null : actvolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.UNIT
     *
     * @return the value of ams_realstorage.UNIT
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.UNIT
     *
     * @param unit the value for ams_realstorage.UNIT
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.LOCATION
     *
     * @return the value of ams_realstorage.LOCATION
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.LOCATION
     *
     * @param location the value for ams_realstorage.LOCATION
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.LIMIT
     *
     * @return the value of ams_realstorage.LIMIT
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.LIMIT
     *
     * @param limit the value for ams_realstorage.LIMIT
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setLimit(String limit) {
        this.limit = limit == null ? null : limit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.DELETETIME
     *
     * @return the value of ams_realstorage.DELETETIME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.DELETETIME
     *
     * @param deletetime the value for ams_realstorage.DELETETIME
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setDeletetime(String deletetime) {
        this.deletetime = deletetime == null ? null : deletetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.DELETEWHY
     *
     * @return the value of ams_realstorage.DELETEWHY
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getDeletewhy() {
        return deletewhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.DELETEWHY
     *
     * @param deletewhy the value for ams_realstorage.DELETEWHY
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setDeletewhy(String deletewhy) {
        this.deletewhy = deletewhy == null ? null : deletewhy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.SERANUM
     *
     * @return the value of ams_realstorage.SERANUM
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getSeranum() {
        return seranum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.SERANUM
     *
     * @param seranum the value for ams_realstorage.SERANUM
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setSeranum(String seranum) {
        this.seranum = seranum == null ? null : seranum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.FD_YEAR
     *
     * @return the value of ams_realstorage.FD_YEAR
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getFdYear() {
        return fdYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.FD_YEAR
     *
     * @param fdYear the value for ams_realstorage.FD_YEAR
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setFdYear(String fdYear) {
        this.fdYear = fdYear == null ? null : fdYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.FD_S
     *
     * @return the value of ams_realstorage.FD_S
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getFdS() {
        return fdS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.FD_S
     *
     * @param fdS the value for ams_realstorage.FD_S
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setFdS(String fdS) {
        this.fdS = fdS == null ? null : fdS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.FD_G
     *
     * @return the value of ams_realstorage.FD_G
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getFdG() {
        return fdG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.FD_G
     *
     * @param fdG the value for ams_realstorage.FD_G
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setFdG(String fdG) {
        this.fdG = fdG == null ? null : fdG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.FD_PAGE
     *
     * @return the value of ams_realstorage.FD_PAGE
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getFdPage() {
        return fdPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.FD_PAGE
     *
     * @param fdPage the value for ams_realstorage.FD_PAGE
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setFdPage(String fdPage) {
        this.fdPage = fdPage == null ? null : fdPage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.STORAGE_REMARK
     *
     * @return the value of ams_realstorage.STORAGE_REMARK
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getStorageRemark() {
        return storageRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.STORAGE_REMARK
     *
     * @param storageRemark the value for ams_realstorage.STORAGE_REMARK
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setStorageRemark(String storageRemark) {
        this.storageRemark = storageRemark == null ? null : storageRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.OTHER1
     *
     * @return the value of ams_realstorage.OTHER1
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.OTHER1
     *
     * @param other1 the value for ams_realstorage.OTHER1
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.OTHER2
     *
     * @return the value of ams_realstorage.OTHER2
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.OTHER2
     *
     * @param other2 the value for ams_realstorage.OTHER2
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_realstorage.OTHER3
     *
     * @return the value of ams_realstorage.OTHER3
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public String getOther3() {
        return other3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_realstorage.OTHER3
     *
     * @param other3 the value for ams_realstorage.OTHER3
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    public void setOther3(String other3) {
        this.other3 = other3 == null ? null : other3.trim();
    }
}