package com.fh.entity.amsmodel;

import java.util.Date;

public class Receive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private Integer rcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.TRANSFNAME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String transfname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.PRODEPART
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String prodepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_NAME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String rcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_DEPART
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String rcDepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_TIME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private Date rcTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_PROGRESS
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String rcProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.CHECKFILE_URL
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String checkfileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_STRING
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String rcString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.RC_REMARK
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String rcRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.REGISTER_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private Integer registerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.PRJ_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private Integer prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.CHECKDETAILS
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String checkdetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.USER_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.PHOTOGRAPH
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String photograph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_receive.AUTOGRAPH
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    private String autograph;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_ID
     *
     * @return the value of ams_receive.RC_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public Integer getRcId() {
        return rcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_ID
     *
     * @param rcId the value for ams_receive.RC_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcId(Integer rcId) {
        this.rcId = rcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.TRANSFNAME
     *
     * @return the value of ams_receive.TRANSFNAME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getTransfname() {
        return transfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.TRANSFNAME
     *
     * @param transfname the value for ams_receive.TRANSFNAME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setTransfname(String transfname) {
        this.transfname = transfname == null ? null : transfname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.PRODEPART
     *
     * @return the value of ams_receive.PRODEPART
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getProdepart() {
        return prodepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.PRODEPART
     *
     * @param prodepart the value for ams_receive.PRODEPART
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setProdepart(String prodepart) {
        this.prodepart = prodepart == null ? null : prodepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_NAME
     *
     * @return the value of ams_receive.RC_NAME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getRcName() {
        return rcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_NAME
     *
     * @param rcName the value for ams_receive.RC_NAME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcName(String rcName) {
        this.rcName = rcName == null ? null : rcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_DEPART
     *
     * @return the value of ams_receive.RC_DEPART
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getRcDepart() {
        return rcDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_DEPART
     *
     * @param rcDepart the value for ams_receive.RC_DEPART
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcDepart(String rcDepart) {
        this.rcDepart = rcDepart == null ? null : rcDepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_TIME
     *
     * @return the value of ams_receive.RC_TIME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public Date getRcTime() {
        return rcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_TIME
     *
     * @param rcTime the value for ams_receive.RC_TIME
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcTime(Date rcTime) {
        this.rcTime = rcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_PROGRESS
     *
     * @return the value of ams_receive.RC_PROGRESS
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getRcProgress() {
        return rcProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_PROGRESS
     *
     * @param rcProgress the value for ams_receive.RC_PROGRESS
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcProgress(String rcProgress) {
        this.rcProgress = rcProgress == null ? null : rcProgress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.CHECKFILE_URL
     *
     * @return the value of ams_receive.CHECKFILE_URL
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getCheckfileUrl() {
        return checkfileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.CHECKFILE_URL
     *
     * @param checkfileUrl the value for ams_receive.CHECKFILE_URL
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setCheckfileUrl(String checkfileUrl) {
        this.checkfileUrl = checkfileUrl == null ? null : checkfileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_STRING
     *
     * @return the value of ams_receive.RC_STRING
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getRcString() {
        return rcString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_STRING
     *
     * @param rcString the value for ams_receive.RC_STRING
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcString(String rcString) {
        this.rcString = rcString == null ? null : rcString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.RC_REMARK
     *
     * @return the value of ams_receive.RC_REMARK
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getRcRemark() {
        return rcRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.RC_REMARK
     *
     * @param rcRemark the value for ams_receive.RC_REMARK
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRcRemark(String rcRemark) {
        this.rcRemark = rcRemark == null ? null : rcRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.REGISTER_ID
     *
     * @return the value of ams_receive.REGISTER_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.REGISTER_ID
     *
     * @param registerId the value for ams_receive.REGISTER_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.PRJ_ID
     *
     * @return the value of ams_receive.PRJ_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public Integer getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.PRJ_ID
     *
     * @param prjId the value for ams_receive.PRJ_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setPrjId(Integer prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.CHECKDETAILS
     *
     * @return the value of ams_receive.CHECKDETAILS
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getCheckdetails() {
        return checkdetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.CHECKDETAILS
     *
     * @param checkdetails the value for ams_receive.CHECKDETAILS
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setCheckdetails(String checkdetails) {
        this.checkdetails = checkdetails == null ? null : checkdetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.USER_ID
     *
     * @return the value of ams_receive.USER_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.USER_ID
     *
     * @param userId the value for ams_receive.USER_ID
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.PHOTOGRAPH
     *
     * @return the value of ams_receive.PHOTOGRAPH
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getPhotograph() {
        return photograph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.PHOTOGRAPH
     *
     * @param photograph the value for ams_receive.PHOTOGRAPH
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setPhotograph(String photograph) {
        this.photograph = photograph == null ? null : photograph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_receive.AUTOGRAPH
     *
     * @return the value of ams_receive.AUTOGRAPH
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public String getAutograph() {
        return autograph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_receive.AUTOGRAPH
     *
     * @param autograph the value for ams_receive.AUTOGRAPH
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    public void setAutograph(String autograph) {
        this.autograph = autograph == null ? null : autograph.trim();
    }
}