package com.fh.entity.amsmodel;

public class Sharepath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_share_path.id
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_share_path.path
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_share_path.account
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_share_path.password
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_share_path.id
     *
     * @return the value of ams_share_path.id
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_share_path.id
     *
     * @param id the value for ams_share_path.id
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_share_path.path
     *
     * @return the value of ams_share_path.path
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_share_path.path
     *
     * @param path the value for ams_share_path.path
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_share_path.account
     *
     * @return the value of ams_share_path.account
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_share_path.account
     *
     * @param account the value for ams_share_path.account
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_share_path.password
     *
     * @return the value of ams_share_path.password
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_share_path.password
     *
     * @param password the value for ams_share_path.password
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}