package com.fh.entity.amsmodel;

import java.util.Date;

public class Storage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.REGISTER_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Integer registerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.REGISTER
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String register;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.REGIST_TIME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.PRJROOT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String prjroot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.DELETE_TIME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.DELETE_WHY
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String deleteWhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.DELETE_PERMISSION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String deletePermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private Integer storageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ams_storage.STORAGE_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    private String storageRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.REGISTER_ID
     *
     * @return the value of ams_storage.REGISTER_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.REGISTER_ID
     *
     * @param registerId the value for ams_storage.REGISTER_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.REGISTER
     *
     * @return the value of ams_storage.REGISTER
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.REGISTER
     *
     * @param register the value for ams_storage.REGISTER
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setRegister(String register) {
        this.register = register == null ? null : register.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.REGIST_TIME
     *
     * @return the value of ams_storage.REGIST_TIME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.REGIST_TIME
     *
     * @param registTime the value for ams_storage.REGIST_TIME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.PRJROOT
     *
     * @return the value of ams_storage.PRJROOT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getPrjroot() {
        return prjroot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.PRJROOT
     *
     * @param prjroot the value for ams_storage.PRJROOT
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setPrjroot(String prjroot) {
        this.prjroot = prjroot == null ? null : prjroot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.DELETE_TIME
     *
     * @return the value of ams_storage.DELETE_TIME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.DELETE_TIME
     *
     * @param deleteTime the value for ams_storage.DELETE_TIME
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.DELETE_WHY
     *
     * @return the value of ams_storage.DELETE_WHY
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getDeleteWhy() {
        return deleteWhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.DELETE_WHY
     *
     * @param deleteWhy the value for ams_storage.DELETE_WHY
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setDeleteWhy(String deleteWhy) {
        this.deleteWhy = deleteWhy == null ? null : deleteWhy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.DELETE_PERMISSION
     *
     * @return the value of ams_storage.DELETE_PERMISSION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getDeletePermission() {
        return deletePermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.DELETE_PERMISSION
     *
     * @param deletePermission the value for ams_storage.DELETE_PERMISSION
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setDeletePermission(String deletePermission) {
        this.deletePermission = deletePermission == null ? null : deletePermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.STORAGE_ID
     *
     * @return the value of ams_storage.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public Integer getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.STORAGE_ID
     *
     * @param storageId the value for ams_storage.STORAGE_ID
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setStorageId(Integer storageId) {
        this.storageId = storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ams_storage.STORAGE_REMARK
     *
     * @return the value of ams_storage.STORAGE_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public String getStorageRemark() {
        return storageRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ams_storage.STORAGE_REMARK
     *
     * @param storageRemark the value for ams_storage.STORAGE_REMARK
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    public void setStorageRemark(String storageRemark) {
        this.storageRemark = storageRemark == null ? null : storageRemark.trim();
    }
}