package com.fh.entity.log;

import java.util.Date;

public class Optlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.id
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.optName
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String optname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.method
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.url
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.ip
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.optTime
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private Date opttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.userId
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.data
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.id
     *
     * @return the value of opt_log.id
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.id
     *
     * @param id the value for opt_log.id
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.optName
     *
     * @return the value of opt_log.optName
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.optName
     *
     * @param optname the value for opt_log.optName
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.method
     *
     * @return the value of opt_log.method
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.method
     *
     * @param method the value for opt_log.method
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.url
     *
     * @return the value of opt_log.url
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.url
     *
     * @param url the value for opt_log.url
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.ip
     *
     * @return the value of opt_log.ip
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.ip
     *
     * @param ip the value for opt_log.ip
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.optTime
     *
     * @return the value of opt_log.optTime
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public Date getOpttime() {
        return opttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.optTime
     *
     * @param opttime the value for opt_log.optTime
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setOpttime(Date opttime) {
        this.opttime = opttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.userId
     *
     * @return the value of opt_log.userId
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.userId
     *
     * @param userid the value for opt_log.userId
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.data
     *
     * @return the value of opt_log.data
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.data
     *
     * @param data the value for opt_log.data
     *
     * @mbggenerated Tue Sep 05 14:10:03 CST 2017
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}