package com.fh.entity.fms;

import java.util.Date;

public class FmsAddFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_addfile.ID
     *
     * @mbggenerated Mon Jul 31 16:05:39 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_addfile.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String fmsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_addfile.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_addfile.PATH
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_addfile.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_addfile.CREATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_addfile.ID
     *
     * @return the value of fms_addfile.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_addfile.ID
     *
     * @param id the value for fms_addfile.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_addfile.fms_ID
     *
     * @return the value of fms_addfile.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getFmsId() {
        return fmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_addfile.fms_ID
     *
     * @param fmsId the value for fms_addfile.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setFmsId(String fmsId) {
        this.fmsId = fmsId == null ? null : fmsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_addfile.NAME
     *
     * @return the value of fms_addfile.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_addfile.NAME
     *
     * @param name the value for fms_addfile.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_addfile.PATH
     *
     * @return the value of fms_addfile.PATH
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_addfile.PATH
     *
     * @param path the value for fms_addfile.PATH
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_addfile.DESC
     *
     * @return the value of fms_addfile.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_addfile.CREATETIME
     *
     * @return the value of fms_addfile.CREATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    public String getDescribe() {
		return describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_addfile.CREATETIME
     *
     * @param createtime the value for fms_addfile.CREATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}