package com.fh.entity.fms;

public class FmsBorrowContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_borrowcontent.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String fmsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_borrowcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_borrowcontent.fms_ID
     *
     * @return the value of fms_borrowcontent.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getFmsId() {
        return fmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_borrowcontent.fms_ID
     *
     * @param fmsId the value for fms_borrowcontent.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setFmsId(String fmsId) {
        this.fmsId = fmsId == null ? null : fmsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_borrowcontent.ID
     *
     * @return the value of fms_borrowcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_borrowcontent.ID
     *
     * @param id the value for fms_borrowcontent.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}