package com.fh.entity.fms;

import java.util.List;

import org.apache.xmlbeans.impl.xb.xsdschema.OpenAttrs;

public class FmsDocBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_docbox.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String id;
    
    
    private Boolean open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_docbox.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String fmsId;



	public Boolean getDrag() {
		return true;
	}



	public String getpId() {
		return fmsId;
	}
    


	public void setpId(String pId) {
	}



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_docbox.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_docbox.VALUE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_docbox.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String describe;
    private Boolean isParent=true;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_docbox.ID
     *
     * @return the value of fms_docbox.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_docbox.ID
     *
     * @param id the value for fms_docbox.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_docbox.fms_ID
     *
     * @return the value of fms_docbox.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getFmsId() {
        return fmsId;
    }

    
  private List<FmsDocBox>  children;
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_docbox.fms_ID
     *
     * @param fmsId the value for fms_docbox.fms_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setFmsId(String fmsId) {
        this.fmsId = fmsId == null ? null : fmsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_docbox.NAME
     *
     * @return the value of fms_docbox.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_docbox.NAME
     *
     * @param name the value for fms_docbox.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_docbox.VALUE
     *
     * @return the value of fms_docbox.VALUE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_docbox.VALUE
     *
     * @param value the value for fms_docbox.VALUE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_docbox.DESC
     *
     * @return the value of fms_docbox.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_docbox.DESC
     *
     * @param desc the value for fms_docbox.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

	public List<FmsDocBox> getChildren() {
		return children;
	}

	public void setChildren(List<FmsDocBox> children) {
		this.children = children;
	}

	public Boolean getOpen() {
		return open;
	}

	public void setOpen(Boolean open) {
		this.open = open;
	}

	public Boolean getIsParent() {
		return isParent;
	}

	public void setIsParent(Boolean isParent) {
		this.isParent = isParent;
	}


    private String url;
    private String target ;

	public String getTarget() {
		return "treeFrame";
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUrl() {
		return "doc/list.do?isvalid=1&fmsid="+id;
	}
    
	
	
    
}