package com.fh.entity.fms;

import java.util.Date;
import java.util.List;

public class FmsDataDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.DATAKEY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String datakey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.ISVALID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Short isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.UPDATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_datadict.CREATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.ID
     *
     * @return the value of fms_datadict.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_datadict.ID
     *
     * @param id the value for fms_datadict.ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.DATAKEY
     *
     * @return the value of fms_datadict.DATAKEY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getDatakey() {
        return datakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_datadict.DATAKEY
     *
     * @param datakey the value for fms_datadict.DATAKEY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDatakey(String datakey) {
        this.datakey = datakey == null ? null : datakey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.NAME
     *
     * @return the value of fms_datadict.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_datadict.NAME
     *
     * @param name the value for fms_datadict.NAME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.ISVALID
     *
     * @return the value of fms_datadict.ISVALID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Short getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_datadict.ISVALID
     *
     * @param isvalid the value for fms_datadict.ISVALID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setIsvalid(Short isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.DESC
     *
     * @return the value of fms_datadict.DESC
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.UPDATETIME
     *
     * @return the value of fms_datadict.UPDATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_datadict.UPDATETIME
     *
     * @param updatetime the value for fms_datadict.UPDATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_datadict.CREATETIME
     *
     * @return the value of fms_datadict.CREATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_datadict.CREATETIME
     *
     * @param createtime the value for fms_datadict.CREATETIME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	public String getDescribe() {
		return describe;
	}

	public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
	}
	private List<FmsDataDictItem> fmsDataDictItems;

	public List<FmsDataDictItem> getFmsDataDictItems() {
		return fmsDataDictItems;
	}

	public void setFmsDataDictItems(List<FmsDataDictItem> fmsDataDictItems) {
		this.fmsDataDictItems = fmsDataDictItems;
	}

	@Override
	public String toString() {
		return "FmsDataDict [id=" + id + ", datakey=" + datakey + ", name=" + name + ", isvalid=" + isvalid
				+ ", describe=" + describe + ", updatetime=" + updatetime + ", createtime=" + createtime
				+ ", fmsDataDictItems=" + fmsDataDictItems + "]";
	}
	
}