package com.fh.entity.fms;

public class FmsPZDoc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.ACDOC_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.AC_VOLUME_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acVolumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.ACDOC_YEAR
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer acdocYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.ACDOC_MONTH
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer acdocMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.ACDOC_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer acdocNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.ACDOC_VALID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer acdocValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.DESTROIED
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String destroied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.DESTROY_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer destroyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.DESTROY_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String destroyHow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdoc.DESTROY_CHECK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String destroyCheck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.ACDOC_ID
     *
     * @return the value of fms_pzdoc.ACDOC_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocId() {
        return acdocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.ACDOC_ID
     *
     * @param acdocId the value for fms_pzdoc.ACDOC_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocId(String acdocId) {
        this.acdocId = acdocId == null ? null : acdocId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.AC_VOLUME_ID
     *
     * @return the value of fms_pzdoc.AC_VOLUME_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcVolumeId() {
        return acVolumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.AC_VOLUME_ID
     *
     * @param acVolumeId the value for fms_pzdoc.AC_VOLUME_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcVolumeId(String acVolumeId) {
        this.acVolumeId = acVolumeId == null ? null : acVolumeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.ACDOC_YEAR
     *
     * @return the value of fms_pzdoc.ACDOC_YEAR
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getAcdocYear() {
        return acdocYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.ACDOC_YEAR
     *
     * @param acdocYear the value for fms_pzdoc.ACDOC_YEAR
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocYear(Integer acdocYear) {
        this.acdocYear = acdocYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.ACDOC_MONTH
     *
     * @return the value of fms_pzdoc.ACDOC_MONTH
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getAcdocMonth() {
        return acdocMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.ACDOC_MONTH
     *
     * @param acdocMonth the value for fms_pzdoc.ACDOC_MONTH
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocMonth(Integer acdocMonth) {
        this.acdocMonth = acdocMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.ACDOC_NUM
     *
     * @return the value of fms_pzdoc.ACDOC_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getAcdocNum() {
        return acdocNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.ACDOC_NUM
     *
     * @param acdocNum the value for fms_pzdoc.ACDOC_NUM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocNum(Integer acdocNum) {
        this.acdocNum = acdocNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.ACDOC_REMARK
     *
     * @return the value of fms_pzdoc.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocRemark() {
        return acdocRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.ACDOC_REMARK
     *
     * @param acdocRemark the value for fms_pzdoc.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocRemark(String acdocRemark) {
        this.acdocRemark = acdocRemark == null ? null : acdocRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.ACDOC_VALID
     *
     * @return the value of fms_pzdoc.ACDOC_VALID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getAcdocValid() {
        return acdocValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.ACDOC_VALID
     *
     * @param acdocValid the value for fms_pzdoc.ACDOC_VALID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocValid(Integer acdocValid) {
        this.acdocValid = acdocValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.DESTROIED
     *
     * @return the value of fms_pzdoc.DESTROIED
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getDestroied() {
        return destroied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.DESTROIED
     *
     * @param destroied the value for fms_pzdoc.DESTROIED
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDestroied(String destroied) {
        this.destroied = destroied == null ? null : destroied.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.DESTROY_ID
     *
     * @return the value of fms_pzdoc.DESTROY_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getDestroyId() {
        return destroyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.DESTROY_ID
     *
     * @param destroyId the value for fms_pzdoc.DESTROY_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDestroyId(Integer destroyId) {
        this.destroyId = destroyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.DESTROY_HOW
     *
     * @return the value of fms_pzdoc.DESTROY_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getDestroyHow() {
        return destroyHow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.DESTROY_HOW
     *
     * @param destroyHow the value for fms_pzdoc.DESTROY_HOW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDestroyHow(String destroyHow) {
        this.destroyHow = destroyHow == null ? null : destroyHow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdoc.DESTROY_CHECK
     *
     * @return the value of fms_pzdoc.DESTROY_CHECK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getDestroyCheck() {
        return destroyCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdoc.DESTROY_CHECK
     *
     * @param destroyCheck the value for fms_pzdoc.DESTROY_CHECK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setDestroyCheck(String destroyCheck) {
        this.destroyCheck = destroyCheck == null ? null : destroyCheck.trim();
    }
}