package com.fh.entity.fms;

public class FmsPZDocBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.AC_BOX_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acBoxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.USER_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.ACDOC_BOX
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer acdocBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.ACDOC_ROOM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.ACDOC_CASE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocCase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.ACDOC_ROW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.ACDOC_COLUME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocColume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocbox.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.AC_BOX_ID
     *
     * @return the value of fms_pzdocbox.AC_BOX_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcBoxId() {
        return acBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.AC_BOX_ID
     *
     * @param acBoxId the value for fms_pzdocbox.AC_BOX_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcBoxId(String acBoxId) {
        this.acBoxId = acBoxId == null ? null : acBoxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.USER_ID
     *
     * @return the value of fms_pzdocbox.USER_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.USER_ID
     *
     * @param userId the value for fms_pzdocbox.USER_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.ACDOC_BOX
     *
     * @return the value of fms_pzdocbox.ACDOC_BOX
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getAcdocBox() {
        return acdocBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.ACDOC_BOX
     *
     * @param acdocBox the value for fms_pzdocbox.ACDOC_BOX
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocBox(Integer acdocBox) {
        this.acdocBox = acdocBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.ACDOC_ROOM
     *
     * @return the value of fms_pzdocbox.ACDOC_ROOM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocRoom() {
        return acdocRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.ACDOC_ROOM
     *
     * @param acdocRoom the value for fms_pzdocbox.ACDOC_ROOM
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocRoom(String acdocRoom) {
        this.acdocRoom = acdocRoom == null ? null : acdocRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.ACDOC_CASE
     *
     * @return the value of fms_pzdocbox.ACDOC_CASE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocCase() {
        return acdocCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.ACDOC_CASE
     *
     * @param acdocCase the value for fms_pzdocbox.ACDOC_CASE
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocCase(String acdocCase) {
        this.acdocCase = acdocCase == null ? null : acdocCase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.ACDOC_ROW
     *
     * @return the value of fms_pzdocbox.ACDOC_ROW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocRow() {
        return acdocRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.ACDOC_ROW
     *
     * @param acdocRow the value for fms_pzdocbox.ACDOC_ROW
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocRow(String acdocRow) {
        this.acdocRow = acdocRow == null ? null : acdocRow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.ACDOC_COLUME
     *
     * @return the value of fms_pzdocbox.ACDOC_COLUME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocColume() {
        return acdocColume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.ACDOC_COLUME
     *
     * @param acdocColume the value for fms_pzdocbox.ACDOC_COLUME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocColume(String acdocColume) {
        this.acdocColume = acdocColume == null ? null : acdocColume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocbox.ACDOC_REMARK
     *
     * @return the value of fms_pzdocbox.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocRemark() {
        return acdocRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocbox.ACDOC_REMARK
     *
     * @param acdocRemark the value for fms_pzdocbox.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocRemark(String acdocRemark) {
        this.acdocRemark = acdocRemark == null ? null : acdocRemark.trim();
    }
}