package com.fh.entity.fms;

import java.util.Date;

public class FmsPZDocVolume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocvolume.AC_VOLUME_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acVolumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocvolume.AC_BOX_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acBoxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocvolume.ACDOC_VOLUME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Integer acdocVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocvolume.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private String acdocRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocvolume.ACDOC_STARTDAY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Date acdocStartday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_pzdocvolume.ACDOC_ENDDAY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    private Date acdocEndday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocvolume.AC_VOLUME_ID
     *
     * @return the value of fms_pzdocvolume.AC_VOLUME_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcVolumeId() {
        return acVolumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocvolume.AC_VOLUME_ID
     *
     * @param acVolumeId the value for fms_pzdocvolume.AC_VOLUME_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcVolumeId(String acVolumeId) {
        this.acVolumeId = acVolumeId == null ? null : acVolumeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocvolume.AC_BOX_ID
     *
     * @return the value of fms_pzdocvolume.AC_BOX_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcBoxId() {
        return acBoxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocvolume.AC_BOX_ID
     *
     * @param acBoxId the value for fms_pzdocvolume.AC_BOX_ID
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcBoxId(String acBoxId) {
        this.acBoxId = acBoxId == null ? null : acBoxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocvolume.ACDOC_VOLUME
     *
     * @return the value of fms_pzdocvolume.ACDOC_VOLUME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Integer getAcdocVolume() {
        return acdocVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocvolume.ACDOC_VOLUME
     *
     * @param acdocVolume the value for fms_pzdocvolume.ACDOC_VOLUME
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocVolume(Integer acdocVolume) {
        this.acdocVolume = acdocVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocvolume.ACDOC_REMARK
     *
     * @return the value of fms_pzdocvolume.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public String getAcdocRemark() {
        return acdocRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocvolume.ACDOC_REMARK
     *
     * @param acdocRemark the value for fms_pzdocvolume.ACDOC_REMARK
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocRemark(String acdocRemark) {
        this.acdocRemark = acdocRemark == null ? null : acdocRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocvolume.ACDOC_STARTDAY
     *
     * @return the value of fms_pzdocvolume.ACDOC_STARTDAY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getAcdocStartday() {
        return acdocStartday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocvolume.ACDOC_STARTDAY
     *
     * @param acdocStartday the value for fms_pzdocvolume.ACDOC_STARTDAY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocStartday(Date acdocStartday) {
        this.acdocStartday = acdocStartday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_pzdocvolume.ACDOC_ENDDAY
     *
     * @return the value of fms_pzdocvolume.ACDOC_ENDDAY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public Date getAcdocEndday() {
        return acdocEndday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_pzdocvolume.ACDOC_ENDDAY
     *
     * @param acdocEndday the value for fms_pzdocvolume.ACDOC_ENDDAY
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    public void setAcdocEndday(Date acdocEndday) {
        this.acdocEndday = acdocEndday;
    }
}