package com.fh.dao;

import java.util.List;

import com.fh.entity.amsmodel.ApplyFile;
import com.fh.util.PageData;

public interface ApplyFileMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ams_apply_file
	 *
	 * @mbggenerated Mon Jul 04 15:29:41 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ams_apply_file
	 *
	 * @mbggenerated Mon Jul 04 15:29:41 CST 2016
	 */
	int insert(ApplyFile record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ams_apply_file
	 *
	 * @mbggenerated Mon Jul 04 15:29:41 CST 2016
	 */
	int insertSelective(ApplyFile record);


	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ams_apply_file
	 *
	 * @mbggenerated Mon Jul 04 15:29:41 CST 2016
	 */
	ApplyFile selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ams_apply_file
	 *
	 * @mbggenerated Mon Jul 04 15:29:41 CST 2016
	 */
	int updateByPrimaryKeySelective(ApplyFile record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ams_apply_file
	 *
	 * @mbggenerated Mon Jul 04 15:29:41 CST 2016
	 */
	int updateByPrimaryKey(ApplyFile record);
	/**
	 * 
	 * @param id
	 * @return
	 * @email:401701706@qq.com
	 * @date:2016年7月14日 下午3:34:30
	 *
	 */
	List<PageData> selectByApplyKey(Integer id);

	
}