package com.fh.dao;

import java.util.List;

import com.fh.entity.Page;
import com.fh.entity.amsmodel.ArchDistribute;
import com.fh.util.PageData;

public interface ArchDistributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int deleteByPrimaryKey(Integer distributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int insert(ArchDistribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int insertSelective(ArchDistribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    ArchDistribute selectByPrimaryKey(Integer distributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int updateByPrimaryKeySelective(ArchDistribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int updateByPrimaryKey(ArchDistribute record);


	List<PageData> selectarchDistributelistPage(Page page);

	List<PageData> selectarchDistributebyarchDistributeId(Integer distributeId);

	List<PageData> selectArchivereByPrimaryKey(Integer id);
}