package com.fh.dao;

import com.fh.entity.amsmodel.ArchDistributeFile;

public interface ArchDistributeFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute_file
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute_file
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int insert(ArchDistributeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute_file
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int insertSelective(ArchDistributeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute_file
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    ArchDistributeFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute_file
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int updateByPrimaryKeySelective(ArchDistributeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_archdistribute_file
     *
     * @mbggenerated Thu Aug 11 10:55:13 CST 2016
     */
    int updateByPrimaryKey(ArchDistributeFile record);
}