package com.fh.dao;

import com.fh.entity.amsmodel.Fdm;

public interface FdmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_fdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int deleteByPrimaryKey(Integer storageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_fdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int insert(Fdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_fdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int insertSelective(Fdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_fdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    Fdm selectByPrimaryKey(Integer storageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_fdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int updateByPrimaryKeySelective(Fdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_fdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int updateByPrimaryKey(Fdm record);
}