package com.fh.dao;

import com.fh.entity.amsmodel.FileCoverage;

public interface FileCoverageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_file_coverage
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    int insert(FileCoverage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_file_coverage
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    int insertSelective(FileCoverage record);
}