package com.fh.dao;

import com.fh.entity.amsmodel.FileDetail;

public interface FileDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_file_detail
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    int insert(FileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_file_detail
     *
     * @mbggenerated Sun Aug 07 16:34:12 CST 2016
     */
    int insertSelective(FileDetail record);
}