package com.fh.dao;

import com.fh.entity.amsmodel.FileXzqh;

public interface FileXzqhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_file_xzqh
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    int insert(FileXzqh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_file_xzqh
     *
     * @mbggenerated Tue Aug 02 10:49:11 CST 2016
     */
    int insertSelective(FileXzqh record);
}