package com.fh.dao;

import com.fh.entity.fms.FmsAddFile;

public interface FmsAddFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_addfile
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_addfile
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsAddFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_addfile
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsAddFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_addfile
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsAddFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_addfile
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsAddFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_addfile
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsAddFile record);
}