package com.fh.dao;

import org.apache.ibatis.annotations.Param;

import com.fh.entity.fms.FmsBorrowContent;

public interface FmsBorrowContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrowcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(@Param("fmsId") String fmsId, @Param("id") String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrowcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsBorrowContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrowcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsBorrowContent record);
}