package com.fh.dao;

import com.fh.entity.fms.FmsBorrow;

public interface FmsBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrow
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrow
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrow
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrow
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsBorrow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrow
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_borrow
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsBorrow record);
}