package com.fh.dao;

import com.fh.entity.fms.FmsDocMain;

public interface FmsDocMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsDocMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsDocMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsDocMain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsDocMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsDocMain record);
}