package com.fh.dao;

import com.fh.entity.fms.FmsDataDict;

public interface FmsDataDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_datadict
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_datadict
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsDataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_datadict
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsDataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_datadict
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsDataDict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_datadict
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsDataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_datadict
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsDataDict record);
}