package com.fh.dao;

import com.fh.entity.fms.FmsDocBox;

public interface FmsDocBoxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docbox
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docbox
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsDocBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docbox
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsDocBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docbox
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsDocBox selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docbox
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsDocBox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_docbox
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsDocBox record);
}