package com.fh.dao;

import com.fh.entity.fms.FmsPZDoc;

public interface FmsPZDocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdoc
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String acdocId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdoc
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsPZDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdoc
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsPZDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdoc
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsPZDoc selectByPrimaryKey(String acdocId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdoc
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsPZDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdoc
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsPZDoc record);
}