package com.fh.dao;

import com.fh.entity.fms.FmsPZDocVolume;

public interface FmsPZDocVolumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdocvolume
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String acVolumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdocvolume
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FmsPZDocVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdocvolume
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FmsPZDocVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdocvolume
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FmsPZDocVolume selectByPrimaryKey(String acVolumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdocvolume
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FmsPZDocVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_pzdocvolume
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FmsPZDocVolume record);
}