package com.fh.dao;

import com.fh.entity.amsmodel.FPKmsLogOperate;

public interface FPKmsLogOperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fpkms_log_operate
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fpkms_log_operate
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(FPKmsLogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fpkms_log_operate
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(FPKmsLogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fpkms_log_operate
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    FPKmsLogOperate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fpkms_log_operate
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(FPKmsLogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fpkms_log_operate
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(FPKmsLogOperate record);
}