package com.fh.dao;

import com.fh.entity.amsmodel.Hdm;

public interface HdmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_hdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int deleteByPrimaryKey(Integer storageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_hdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int insert(Hdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_hdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int insertSelective(Hdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_hdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    Hdm selectByPrimaryKey(Integer storageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_hdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int updateByPrimaryKeySelective(Hdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_hdm
     *
     * @mbggenerated Tue Aug 09 09:42:51 CST 2016
     */
    int updateByPrimaryKey(Hdm record);
}