package com.fh.dao;

import com.fh.entity.amsmodel.KmsAddFile;

public interface KmsAddFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_addfile
     *
     * @mbggenerated Mon Feb 05 03:14:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_addfile
     *
     * @mbggenerated Mon Feb 05 03:14:58 CST 2018
     */
    int insert(KmsAddFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_addfile
     *
     * @mbggenerated Mon Feb 05 03:14:58 CST 2018
     */
    int insertSelective(KmsAddFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_addfile
     *
     * @mbggenerated Mon Feb 05 03:14:58 CST 2018
     */
    KmsAddFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_addfile
     *
     * @mbggenerated Mon Feb 05 03:14:58 CST 2018
     */
    int updateByPrimaryKeySelective(KmsAddFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_addfile
     *
     * @mbggenerated Mon Feb 05 03:14:58 CST 2018
     */
    int updateByPrimaryKey(KmsAddFile record);
}