package com.fh.dao;

import com.fh.entity.amsmodel.KmsData;
import com.fh.entity.amsmodel.KmsDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KmsDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int countByExample(KmsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int deleteByExample(KmsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int deleteByPrimaryKey(Integer kdataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int insert(KmsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int insertSelective(KmsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    List<KmsData> selectByExample(KmsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    KmsData selectByPrimaryKey(Integer kdataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") KmsData record, @Param("example") KmsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int updateByExample(@Param("record") KmsData record, @Param("example") KmsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int updateByPrimaryKeySelective(KmsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_data
     *
     * @mbggenerated Wed Aug 16 11:38:43 CST 2017
     */
    int updateByPrimaryKey(KmsData record);
}