package com.fh.dao;

import com.fh.entity.amsmodel.KmsFile;

public interface KmsFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_file
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    int deleteByPrimaryKey(Integer kfileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_file
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    int insert(KmsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_file
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    int insertSelective(KmsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_file
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    KmsFile selectByPrimaryKey(Integer kfileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_file
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    int updateByPrimaryKeySelective(KmsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_file
     *
     * @mbggenerated Mon Sep 18 18:10:52 CST 2017
     */
    int updateByPrimaryKey(KmsFile record);
}