package com.fh.dao;

import com.fh.entity.amsmodel.KmsFiles;

public interface KmsFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_files
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    int deleteByPrimaryKey(Integer kfilesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_files
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    int insert(KmsFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_files
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    int insertSelective(KmsFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_files
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    KmsFiles selectByPrimaryKey(Integer kfilesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_files
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    int updateByPrimaryKeySelective(KmsFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_files
     *
     * @mbggenerated Wed Aug 23 15:20:15 CST 2017
     */
    int updateByPrimaryKey(KmsFiles record);
}