package com.fh.dao;

import com.fh.entity.amsmodel.KmsRuKuContent;

public interface KmsRuKuContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_rukucontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_rukucontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(KmsRuKuContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_rukucontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(KmsRuKuContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_rukucontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    KmsRuKuContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_rukucontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(KmsRuKuContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_rukucontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(KmsRuKuContent record);
}