package com.fh.dao;

import com.fh.entity.amsmodel.KmsSendContent;

public interface KmsSendContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_sendcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_sendcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(KmsSendContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_sendcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(KmsSendContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_sendcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    KmsSendContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_sendcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(KmsSendContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kms_sendcontent
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(KmsSendContent record);
}