package com.fh.dao;

import com.fh.entity.amsmodel.PmsDocMain;

public interface PmsDocMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String pfileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(PmsDocMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(PmsDocMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    PmsDocMain selectByPrimaryKey(String pfileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(PmsDocMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_docmain
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(PmsDocMain record);
}