package com.fh.dao;

import com.fh.entity.amsmodel.PmsPInformation;

public interface PmsPInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pinformation
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pinformation
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(PmsPInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pinformation
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(PmsPInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pinformation
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    PmsPInformation selectByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pinformation
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(PmsPInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pinformation
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(PmsPInformation record);
}