package com.fh.dao;

import com.fh.entity.amsmodel.PmsPExperience;

public interface PmsPExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pexperience
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    int deleteByPrimaryKey(String pExId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pexperience
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    int insert(PmsPExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pexperience
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    int insertSelective(PmsPExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pexperience
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    PmsPExperience selectByPrimaryKey(String pExId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pexperience
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    int updateByPrimaryKeySelective(PmsPExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pexperience
     *
     * @mbggenerated Wed Aug 23 14:40:43 CST 2017
     */
    int updateByPrimaryKey(PmsPExperience record);
}