package com.fh.dao;

import com.fh.entity.amsmodel.PmsPFileType;

public interface PmsPFileTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pfiletype
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int deleteByPrimaryKey(String pfileTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pfiletype
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insert(PmsPFileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pfiletype
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int insertSelective(PmsPFileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pfiletype
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    PmsPFileType selectByPrimaryKey(String pfileTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pfiletype
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKeySelective(PmsPFileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_pfiletype
     *
     * @mbggenerated Mon Jul 31 16:05:40 CST 2017
     */
    int updateByPrimaryKey(PmsPFileType record);
}