package com.fh.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.fh.entity.Page;
import com.fh.entity.amsmodel.Prjtype;
import com.fh.util.PageData;
@Repository("prjtypeMapper")
public interface PrjtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_prjtype
     *
     * @mbggenerated Wed May 25 16:37:06 CST 2016
     */
    int deleteByPrimaryKey(Integer prjtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_prjtype
     *
     * @mbggenerated Wed May 25 16:37:06 CST 2016
     */
    int insert(Prjtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_prjtype
     *
     * @mbggenerated Wed May 25 16:37:06 CST 2016
     */
    int insertSelective(Prjtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_prjtype
     *
     * @mbggenerated Wed May 25 16:37:06 CST 2016
     */
    Prjtype selectByPrimaryKey(Integer prjtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_prjtype
     *
     * @mbggenerated Wed May 25 16:37:06 CST 2016
     */
    int updateByPrimaryKeySelective(Prjtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_prjtype
     *
     * @mbggenerated Wed May 25 16:37:06 CST 2016
     */
    int updateByPrimaryKey(Prjtype record);
    
    
    
	/**
	 * 查找对象
	 * @param str
	 * @param obj
	 * @return
	 * @throws Exception
	 */
	public List<PageData> selectAll(String str, PageData pd) throws Exception;
	

    
    
}