package com.fh.dao;

import com.fh.entity.amsmodel.RealStorage;

public interface RealStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_realstorage
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    int deleteByPrimaryKey(Integer realstorageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_realstorage
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    int insert(RealStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_realstorage
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    int insertSelective(RealStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_realstorage
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    RealStorage selectByPrimaryKey(Integer realstorageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_realstorage
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    int updateByPrimaryKeySelective(RealStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_realstorage
     *
     * @mbggenerated Tue Aug 09 11:30:22 CST 2016
     */
    int updateByPrimaryKey(RealStorage record);
}