package com.fh.dao;

import com.fh.entity.amsmodel.Receive;

public interface ReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_receive
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    int deleteByPrimaryKey(Integer rcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_receive
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    int insert(Receive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_receive
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    int insertSelective(Receive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_receive
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    Receive selectByPrimaryKey(Integer rcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_receive
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    int updateByPrimaryKeySelective(Receive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_receive
     *
     * @mbggenerated Thu Dec 15 11:18:22 CST 2016
     */
    int updateByPrimaryKey(Receive record);
}