package com.fh.dao;

import com.fh.entity.amsmodel.Sharepathuser;
import com.fh.util.PageData;

public interface SharepathuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_path_user
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_path_user
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    int insert(Sharepathuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_path_user
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    int insertSelective(Sharepathuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_path_user
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    Sharepathuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_path_user
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    int updateByPrimaryKeySelective(Sharepathuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ams_path_user
     *
     * @mbggenerated Mon Jul 25 16:16:52 CST 2016
     */
    int updateByPrimaryKey(Sharepathuser record);

	PageData selectPathbyuserId(String u);
}